DGtalTools: DGtal::DECImage2D< TKSpace, TLinearAlgebra > Struct Template Reference
DGtal::DECImage2D< TKSpace, TLinearAlgebra > Struct Template Reference
#include <imageProcessing/DECImageHelpers.h>
Public Types
typedef TKSpace KSpace
typedef TLinearAlgebra LinearAlgebra
typedef KSpace::Space Space
typedef Space::Point Point
typedef Space::RealVector RealVector
typedef RealVector::Component Scalar
typedef KSpace::SCell SCell
typedef KSpace::Cell Cell
typedef KSpace::Surfel Surfel
typedef HyperRectDomain< Space > Domain
typedef DiscreteExteriorCalculus< 2, 2, LinearAlgebra > Calculus
typedef DiscreteExteriorCalculusFactory< LinearAlgebra > CalculusFactory
typedef Calculus::Index Index
typedef Calculus::PrimalForm0 PrimalForm0
typedef Calculus::PrimalForm1 PrimalForm1
typedef Calculus::PrimalForm2 PrimalForm2
typedef Calculus::PrimalIdentity0 PrimalIdentity0
typedef Calculus::PrimalIdentity1 PrimalIdentity1
typedef Calculus::PrimalIdentity2 PrimalIdentity2
typedef Calculus::PrimalDerivative0 PrimalDerivative0
typedef Calculus::PrimalDerivative1 PrimalDerivative1
typedef Calculus::DualDerivative0 DualDerivative0
typedef Calculus::DualDerivative1 DualDerivative1
typedef Calculus::PrimalAntiderivative1 PrimalAntiderivative1
typedef Calculus::PrimalAntiderivative2 PrimalAntiderivative2
typedef Calculus::DualAntiderivative1 DualAntiderivative1
typedef Calculus::DualAntiderivative2 DualAntiderivative2
typedef Calculus::PrimalHodge0 PrimalHodge0
typedef Calculus::PrimalHodge1 PrimalHodge1
typedef Calculus::PrimalHodge2 PrimalHodge2
typedef Calculus::DualHodge0 DualHodge0
typedef Calculus::DualHodge1 DualHodge1
typedef Calculus::DualHodge2 DualHodge2
typedef LinearAlgebra::SolverSimplicialLLT LinearAlgebraSolver
typedef DiscreteExteriorCalculusSolver< Calculus, LinearAlgebraSolver, 0, PRIMAL, 0, PRIMAL > SolverU
typedef DiscreteExteriorCalculusSolver< Calculus, LinearAlgebraSolver, 1, PRIMAL, 1, PRIMAL > SolverV
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CCellularGridSpaceND< KSpace >))
BOOST_STATIC_ASSERT ((KSpace::dimension==2))
~DECImage2D ()=default
DECImage2D (int _verbose=1)
void init (Clone< KSpace > aKSpace)
DECImage2D (const DECImage2D &other)=delete
DECImage2D (DECImage2D &&other)=delete
DECImage2D & operator= (const DECImage2D &other)=delete
DECImage2D & operator= (DECImage2D &&other)=delete
Data Fields
int verbose
Calculus calculus
Domain domain
Domain cell_domain
PrimalDerivative0 D0
PrimalDerivative1 D1
DualDerivative0 dual_D0
DualDerivative1 dual_D1
PrimalHodge0 primal_h0
PrimalHodge1 primal_h1
PrimalHodge2 primal_h2
DualHodge0 dual_h0
DualHodge1 dual_h1
DualHodge2 dual_h2
Detailed Description
template<typename TKSpace, typename TLinearAlgebra = EigenLinearAlgebraBackend>
struct DGtal::DECImage2D< TKSpace, TLinearAlgebra >
Aim: This class simplifies the development of 2D image processing tools using discrete exterior calculus. Most notably it take care of initializing correctly a discrete exterior calculus in some 2D domain, and precomputes derivative and Hodge star operators. You may have a look at module Image restoration and inpainting with Ambrosio-Tortorelli functional for such image processing tools and more explanation on discrete calculus.
Description of template class 'DECImage2D'
Template Parameters
TKSpace any model of CCellularGridSpaceND, e.g KhalimskySpaceND
TLinearAlgebra any back-end for performing linear algebra, default is EigenLinearAlgebraBackend.
See also
ATu0v1
ATu2v0
Definition at line 741 of file DECImageHelpers.h.
Member Typedef Documentation
Calculus
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef DiscreteExteriorCalculus<2,2, LinearAlgebra> DGtal::DECImage2D< TKSpace, TLinearAlgebra >::Calculus
Definition at line 753 of file DECImageHelpers.h.
CalculusFactory
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef DiscreteExteriorCalculusFactory<LinearAlgebra> DGtal::DECImage2D< TKSpace, TLinearAlgebra >::CalculusFactory
Definition at line 754 of file DECImageHelpers.h.
Cell
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef KSpace::Cell DGtal::DECImage2D< TKSpace, TLinearAlgebra >::Cell
Definition at line 750 of file DECImageHelpers.h.
Domain
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef HyperRectDomain<Space> DGtal::DECImage2D< TKSpace, TLinearAlgebra >::Domain
Definition at line 752 of file DECImageHelpers.h.
DualAntiderivative1
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::DualAntiderivative1 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::DualAntiderivative1
Definition at line 768 of file DECImageHelpers.h.
DualAntiderivative2
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::DualAntiderivative2 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::DualAntiderivative2
Definition at line 769 of file DECImageHelpers.h.
DualDerivative0
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::DualDerivative0 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::DualDerivative0
Definition at line 764 of file DECImageHelpers.h.
DualDerivative1
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::DualDerivative1 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::DualDerivative1
Definition at line 765 of file DECImageHelpers.h.
DualHodge0
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::DualHodge0 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::DualHodge0
Definition at line 773 of file DECImageHelpers.h.
DualHodge1
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::DualHodge1 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::DualHodge1
Definition at line 774 of file DECImageHelpers.h.
DualHodge2
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::DualHodge2 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::DualHodge2
Definition at line 775 of file DECImageHelpers.h.
Index
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::Index DGtal::DECImage2D< TKSpace, TLinearAlgebra >::Index
Definition at line 755 of file DECImageHelpers.h.
KSpace
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef TKSpace DGtal::DECImage2D< TKSpace, TLinearAlgebra >::KSpace
Definition at line 742 of file DECImageHelpers.h.
LinearAlgebra
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef TLinearAlgebra DGtal::DECImage2D< TKSpace, TLinearAlgebra >::LinearAlgebra
Definition at line 743 of file DECImageHelpers.h.
LinearAlgebraSolver
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef LinearAlgebra::SolverSimplicialLLT DGtal::DECImage2D< TKSpace, TLinearAlgebra >::LinearAlgebraSolver
Definition at line 776 of file DECImageHelpers.h.
Point
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Space::Point DGtal::DECImage2D< TKSpace, TLinearAlgebra >::Point
Definition at line 746 of file DECImageHelpers.h.
PrimalAntiderivative1
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalAntiderivative1 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalAntiderivative1
Definition at line 766 of file DECImageHelpers.h.
PrimalAntiderivative2
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalAntiderivative2 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalAntiderivative2
Definition at line 767 of file DECImageHelpers.h.
PrimalDerivative0
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalDerivative0 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalDerivative0
Definition at line 762 of file DECImageHelpers.h.
PrimalDerivative1
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalDerivative1 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalDerivative1
Definition at line 763 of file DECImageHelpers.h.
PrimalForm0
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalForm0 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalForm0
Definition at line 756 of file DECImageHelpers.h.
PrimalForm1
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalForm1 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalForm1
Definition at line 757 of file DECImageHelpers.h.
PrimalForm2
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalForm2 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalForm2
Definition at line 758 of file DECImageHelpers.h.
PrimalHodge0
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalHodge0 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalHodge0
Definition at line 770 of file DECImageHelpers.h.
PrimalHodge1
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalHodge1 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalHodge1
Definition at line 771 of file DECImageHelpers.h.
PrimalHodge2
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalHodge2 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalHodge2
Definition at line 772 of file DECImageHelpers.h.
PrimalIdentity0
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalIdentity0 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalIdentity0
Definition at line 759 of file DECImageHelpers.h.
PrimalIdentity1
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalIdentity1 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalIdentity1
Definition at line 760 of file DECImageHelpers.h.
PrimalIdentity2
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Calculus::PrimalIdentity2 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::PrimalIdentity2
Definition at line 761 of file DECImageHelpers.h.
RealVector
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef Space::RealVector DGtal::DECImage2D< TKSpace, TLinearAlgebra >::RealVector
Definition at line 747 of file DECImageHelpers.h.
Scalar
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef RealVector::Component DGtal::DECImage2D< TKSpace, TLinearAlgebra >::Scalar
Definition at line 748 of file DECImageHelpers.h.
SCell
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef KSpace::SCell DGtal::DECImage2D< TKSpace, TLinearAlgebra >::SCell
Definition at line 749 of file DECImageHelpers.h.
SolverU
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef DiscreteExteriorCalculusSolver<Calculus, LinearAlgebraSolver, 0, PRIMAL, 0, PRIMAL> DGtal::DECImage2D< TKSpace, TLinearAlgebra >::SolverU
Definition at line 778 of file DECImageHelpers.h.
SolverV
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef DiscreteExteriorCalculusSolver<Calculus, LinearAlgebraSolver, 1, PRIMAL, 1, PRIMAL> DGtal::DECImage2D< TKSpace, TLinearAlgebra >::SolverV
Definition at line 780 of file DECImageHelpers.h.
Space
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef KSpace::Space DGtal::DECImage2D< TKSpace, TLinearAlgebra >::Space
Definition at line 745 of file DECImageHelpers.h.
Surfel
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> typedef KSpace::Surfel DGtal::DECImage2D< TKSpace, TLinearAlgebra >::Surfel
Definition at line 751 of file DECImageHelpers.h.
Constructor & Destructor Documentation
~DECImage2D()
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DGtal::DECImage2D< TKSpace, TLinearAlgebra >::~DECImage2D () default
Destructor.
DECImage2D() [1/3]
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DGtal::DECImage2D< TKSpace, TLinearAlgebra >::DECImage2D (int _verbose = 1) inline
Default constructor. The object needs to be initialized with init.
Parameters
_verbose specifies the verbose level (0: silent, 1: more info ...).
Definition at line 796 of file DECImageHelpers.h.
      : verbose( _verbose ),
        calculus(),
        D0( calculus ), D1( calculus ),
        dual_D0( calculus ), dual_D1( calculus ),
        primal_h0( calculus ), primal_h1( calculus ), primal_h2( calculus ),
        dual_h0( calculus ), dual_h1( calculus ), dual_h2( calculus )
    {}
DECImage2D() [2/3]
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DGtal::DECImage2D< TKSpace, TLinearAlgebra >::DECImage2D (const DECImage2D< TKSpace, TLinearAlgebra > & other) delete
Copy constructor.
Parameters
other the object to clone.
DECImage2D() [3/3]
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DGtal::DECImage2D< TKSpace, TLinearAlgebra >::DECImage2D (DECImage2D< TKSpace, TLinearAlgebra > && other) delete
Move constructor.
Parameters
other the object to move.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DGtal::DECImage2D< TKSpace, TLinearAlgebra >::BOOST_CONCEPT_ASSERT ((concepts::CCellularGridSpaceND< KSpace >))
BOOST_STATIC_ASSERT()
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DGtal::DECImage2D< TKSpace, TLinearAlgebra >::BOOST_STATIC_ASSERT ((KSpace::dimension==2))
init()
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> void DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init (Clone< KSpace > aKSpace) inline
Constructor from cellular grid space, which specifies the domain of calculus.
Parameters
aKSpace the cellular grid space specifies the domain of calculus (i.e. all the cells and incidence), which is cloned inside the class.
Definition at line 812 of file DECImageHelpers.h.
    {
      calculus.myKSpace = aKSpace;
      const KSpace & K  = calculus.myKSpace;
      domain            = Domain( K.lowerBound(), K.upperBound() );
      Point  p0         = K.uKCoords( K.lowerCell() );
      Point  p1         = K.uKCoords( K.upperCell() );
      cell_domain       = Domain( p0, p1 );
      if ( verbose > 0 ) trace.beginBlock("building AT functionnals");
      // Adds all the cell
      for ( typename Domain::ConstIterator it = cell_domain.begin(), itE = cell_domain.end();
            it != itE; ++it )
        calculus.insertSCell( K.sCell( *it ) ); // ajoute toutes les cellules de Khalimsky.
      calculus.updateIndexes();
      if ( verbose > 1 ) trace.info() << calculus << std::endl;
      // Precomputes operators.
      if ( verbose > 1 ) trace.info() << "primal_D0" << std::endl;
      D0 = calculus.template derivative<0,PRIMAL>();
      if ( verbose > 1 ) trace.info() << "primal_D1" << std::endl;
      D1 = calculus.template derivative<1,PRIMAL>();
      if ( verbose > 1 ) trace.info() << "dual_D0" << std::endl;
      dual_D0   = calculus.template derivative<0,DUAL>();
      if ( verbose > 1 ) trace.info() << "dual_D1" << std::endl;
      dual_D1   = calculus.template derivative<1,DUAL>();
      if ( verbose > 1 ) trace.info() << "primal_h1" << std::endl;
      primal_h0 = calculus.template hodge<0,PRIMAL>();
      if ( verbose > 1 ) trace.info() << "primal_h1" << std::endl;
      primal_h1 = calculus.template hodge<1,PRIMAL>();
      if ( verbose > 1 ) trace.info() << "primal_h2" << std::endl;
      primal_h2 = calculus.template hodge<2,PRIMAL>();
      if ( verbose > 1 ) trace.info() << "dual_h1" << std::endl;
      dual_h0   = calculus.template hodge<0,DUAL>();
      if ( verbose > 1 ) trace.info() << "dual_h1" << std::endl;
      dual_h1   = calculus.template hodge<1,DUAL>();
      if ( verbose > 1 ) trace.info() << "dual_h2" << std::endl;
      dual_h2   = calculus.template hodge<2,DUAL>();
      if ( verbose > 0 ) trace.endBlock();
    }
References HyperRectDomain< Space >::begin(), DGtal::Trace::beginBlock(), DGtal::DECImage2D< TKSpace, TLinearAlgebra >::calculus, DGtal::DECImage2D< TKSpace, TLinearAlgebra >::cell_domain, DGtal::DECImage2D< TKSpace, TLinearAlgebra >::D0, DGtal::DECImage2D< TKSpace, TLinearAlgebra >::D1, DGtal::DECImage2D< TKSpace, TLinearAlgebra >::domain, DGtal::DECImage2D< TKSpace, TLinearAlgebra >::dual_D0, DGtal::DECImage2D< TKSpace, TLinearAlgebra >::dual_D1, DGtal::DECImage2D< TKSpace, TLinearAlgebra >::dual_h0, DGtal::DECImage2D< TKSpace, TLinearAlgebra >::dual_h1, DGtal::DECImage2D< TKSpace, TLinearAlgebra >::dual_h2, HyperRectDomain< Space >::end(), DGtal::Trace::endBlock(), DGtal::Trace::info(), DGtal::DiscreteExteriorCalculus< dimEmbedded, dimAmbient, TLinearAlgebraBackend, TInteger >::insertSCell(), DGtal::DiscreteExteriorCalculus< dimEmbedded, dimAmbient, TLinearAlgebraBackend, TInteger >::myKSpace, DGtal::DECImage2D< TKSpace, TLinearAlgebra >::primal_h0, DGtal::DECImage2D< TKSpace, TLinearAlgebra >::primal_h1, DGtal::DECImage2D< TKSpace, TLinearAlgebra >::primal_h2, DGtal::trace, DGtal::DiscreteExteriorCalculus< dimEmbedded, dimAmbient, TLinearAlgebraBackend, TInteger >::updateIndexes(), and DGtal::DECImage2D< TKSpace, TLinearAlgebra >::verbose.
operator=() [1/2]
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DECImage2D & DGtal::DECImage2D< TKSpace, TLinearAlgebra >::operator= (const DECImage2D< TKSpace, TLinearAlgebra > & other) delete
Copy assignment operator.
Parameters
other the object to copy.
Returns
a reference on 'this'.
operator=() [2/2]
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DECImage2D & DGtal::DECImage2D< TKSpace, TLinearAlgebra >::operator= (DECImage2D< TKSpace, TLinearAlgebra > && other) delete
Move assignment operator.
Parameters
other the object to move.
Returns
a reference on 'this'.
Field Documentation
calculus
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> Calculus DGtal::DECImage2D< TKSpace, TLinearAlgebra >::calculus
The discrete exterior calculus instance.
Definition at line 884 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
cell_domain
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> Domain DGtal::DECImage2D< TKSpace, TLinearAlgebra >::cell_domain
The cell domain (i.e. all the cells)
Definition at line 888 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
D0
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> PrimalDerivative0 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::D0
primal derivative: 0-form -> 1-form
Definition at line 890 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
D1
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> PrimalDerivative1 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::D1
primal derivative: 1-form -> 2-form
Definition at line 892 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
domain
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> Domain DGtal::DECImage2D< TKSpace, TLinearAlgebra >::domain
The image domain (i.e. all the pixels)
Definition at line 886 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
dual_D0
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DualDerivative0 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::dual_D0
dual derivative dual 0-form -> dual 1-form
Definition at line 894 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
dual_D1
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DualDerivative1 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::dual_D1
dual derivative dual 1-form -> dual 2-form
Definition at line 896 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
dual_h0
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DualHodge0 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::dual_h0
hodge star: dual 0-form -> 0-form
Definition at line 904 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
dual_h1
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DualHodge1 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::dual_h1
hodge star: dual 1-form -> 1-form
Definition at line 906 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
dual_h2
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> DualHodge2 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::dual_h2
hodge star: dual 2-form -> 2-form
Definition at line 908 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
primal_h0
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> PrimalHodge0 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::primal_h0
hodge star: 0-form -> dual 0-form
Definition at line 898 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
primal_h1
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> PrimalHodge1 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::primal_h1
hodge star: 1-form -> dual 1-form
Definition at line 900 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
primal_h2
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> PrimalHodge2 DGtal::DECImage2D< TKSpace, TLinearAlgebra >::primal_h2
hodge star: 2-form -> dual 2-form
Definition at line 902 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
verbose
template<typename TKSpace , typename TLinearAlgebra = EigenLinearAlgebraBackend> int DGtal::DECImage2D< TKSpace, TLinearAlgebra >::verbose
The verbose level (0: silent).
Definition at line 882 of file DECImageHelpers.h.
Referenced by DGtal::DECImage2D< TKSpace, TLinearAlgebra >::init().
The documentation for this struct was generated from the following file:
DECImageHelpers.h