var searchData=
[
  ['sametype',['SameType',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1concepts_1_1ConceptUtils_1_1SameType.html',1,'DGtal::concepts::ConceptUtils']]],
  ['sametype_3c_20t_2c_20t_20_3e',['SameType&lt; T, T &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1concepts_1_1ConceptUtils_1_1SameType_3_01T_00_01T_01_4.html',1,'DGtal::concepts::ConceptUtils']]],
  ['saturatedsegmentation',['SaturatedSegmentation',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SaturatedSegmentation.html',1,'DGtal']]],
  ['scellmap',['SCellMap',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1KhalimskySpaceND_1_1SCellMap.html',1,'DGtal::KhalimskySpaceND&lt; dim, TInteger &gt;::SCellMap&lt; class &gt;'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1KhalimskyPreSpaceND_1_1SCellMap.html',1,'DGtal::KhalimskyPreSpaceND&lt; dim, TInteger &gt;::SCellMap&lt; class &gt;']]],
  ['scelltoarrow',['SCellToArrow',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToArrow.html',1,'DGtal::functors']]],
  ['scelltocode',['SCellToCode',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToCode.html',1,'DGtal::functors']]],
  ['scelltoincidentpoints',['SCellToIncidentPoints',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToIncidentPoints.html',1,'DGtal::functors']]],
  ['scelltoinnerpoint',['SCellToInnerPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToInnerPoint.html',1,'DGtal::functors']]],
  ['scelltomidpoint',['SCellToMidPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1deprecated_1_1SCellToMidPoint.html',1,'DGtal::functors::deprecated']]],
  ['scelltoouterpoint',['SCellToOuterPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToOuterPoint.html',1,'DGtal::functors']]],
  ['scelltopoint',['SCellToPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToPoint.html',1,'DGtal::functors']]],
  ['segmentcomputeriterator',['SegmentComputerIterator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SaturatedSegmentation_1_1SegmentComputerIterator.html',1,'DGtal::SaturatedSegmentation&lt; TSegmentComputer &gt;::SegmentComputerIterator'],['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1GreedySegmentation_1_1SegmentComputerIterator.html',1,'DGtal::GreedySegmentation&lt; TSegmentComputer &gt;::SegmentComputerIterator']]],
  ['segmentcomputertraits',['SegmentComputerTraits',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SegmentComputerTraits.html',1,'DGtal']]],
  ['selectcallbackfctstore',['SelectCallbackFctStore',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1Display3D_1_1SelectCallbackFctStore.html',1,'DGtal::Display3D']]],
  ['separablemetricadapter',['SeparableMetricAdapter',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SeparableMetricAdapter.html',1,'DGtal']]],
  ['sequence',['Sequence',['https://dgtal-team.github.io/doc-nightly/structboost_1_1Sequence.html',1,'boost']]],
  ['sequencecategory',['SequenceCategory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SequenceCategory.html',1,'DGtal']]],
  ['setassociativecategory',['SetAssociativeCategory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetAssociativeCategory.html',1,'DGtal']]],
  ['setfromimage',['SetFromImage',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetFromImage.html',1,'DGtal']]],
  ['setfunctionsimpl',['SetFunctionsImpl',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1SetFunctionsImpl.html',1,'DGtal::detail']]],
  ['setfunctionsimpl_3c_20container_2c_20false_2c_20true_20_3e',['SetFunctionsImpl&lt; Container, false, true &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1SetFunctionsImpl_3_01Container_00_01false_00_01true_01_4.html',1,'DGtal::detail']]],
  ['setfunctionsimpl_3c_20container_2c_20true_2c_20false_20_3e',['SetFunctionsImpl&lt; Container, true, false &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1SetFunctionsImpl_3_01Container_00_01true_00_01false_01_4.html',1,'DGtal::detail']]],
  ['setfunctionsimpl_3c_20container_2c_20true_2c_20true_20_3e',['SetFunctionsImpl&lt; Container, true, true &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1SetFunctionsImpl_3_01Container_00_01true_00_01true_01_4.html',1,'DGtal::detail']]],
  ['setmode',['SetMode',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetMode.html',1,'DGtal']]],
  ['setmode3d',['SetMode3D',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetMode3D.html',1,'DGtal']]],
  ['setname3d',['SetName3D',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetName3D.html',1,'DGtal']]],
  ['setofsurfels',['SetOfSurfels',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SetOfSurfels.html',1,'DGtal']]],
  ['setpredicate',['SetPredicate',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1deprecated_1_1SetPredicate.html',1,'DGtal::deprecated']]],
  ['setselectcallback3d',['SetSelectCallback3D',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetSelectCallback3D.html',1,'DGtal']]],
  ['setvalueiterator',['SetValueIterator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SetValueIterator.html',1,'DGtal']]],
  ['sgiassignable',['SGIAssignable',['https://dgtal-team.github.io/doc-nightly/structboost_1_1SGIAssignable.html',1,'boost']]],
  ['shape',['Shape',['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1Shape.html',1,'LibBoard']]],
  ['shapelist',['ShapeList',['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1ShapeList.html',1,'LibBoard']]],
  ['shapemeancurvaturefunctor',['ShapeMeanCurvatureFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeMeanCurvatureFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapenormalvectorfunctor',['ShapeNormalVectorFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeNormalVectorFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapepositionfunctor',['ShapePositionFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapePositionFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapes',['Shapes',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Shapes.html',1,'DGtal']]],
  ['signal',['Signal',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Signal.html',1,'DGtal']]],
  ['signal_3c_20value_20_3e',['Signal&lt; Value &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Signal.html',1,'Signal&lt; Value &gt;'],['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Signal.html',1,'DGtal::Signal&lt; Value &gt;']]],
  ['signaldata',['SignalData',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignalData.html',1,'DGtal']]],
  ['signedinteger',['SignedInteger',['https://dgtal-team.github.io/doc-nightly/structboost_1_1SignedInteger.html',1,'boost']]],
  ['signedkhalimskycell',['SignedKhalimskyCell',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignedKhalimskyCell.html',1,'DGtal']]],
  ['signedkhalimskyprecell',['SignedKhalimskyPreCell',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignedKhalimskyPreCell.html',1,'DGtal']]],
  ['signedkhalimskyprecell_3c_20dim_2c_20integer_20_3e',['SignedKhalimskyPreCell&lt; dim, Integer &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignedKhalimskyPreCell.html',1,'SignedKhalimskyPreCell&lt; dim, Integer &gt;'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignedKhalimskyPreCell.html',1,'DGtal::SignedKhalimskyPreCell&lt; dim, Integer &gt;']]],
  ['simple2x2detcomputer',['Simple2x2DetComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Simple2x2DetComputer.html',1,'DGtal']]],
  ['simple2x2detcomputer_3c_20integer_20_3e',['Simple2x2DetComputer&lt; Integer &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Simple2x2DetComputer.html',1,'Simple2x2DetComputer&lt; Integer &gt;'],['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Simple2x2DetComputer.html',1,'DGtal::Simple2x2DetComputer&lt; Integer &gt;']]],
  ['simpleassociativecategory',['SimpleAssociativeCategory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleAssociativeCategory.html',1,'DGtal']]],
  ['simpleassociativecontainer',['SimpleAssociativeContainer',['https://dgtal-team.github.io/doc-nightly/structboost_1_1SimpleAssociativeContainer.html',1,'boost']]],
  ['simpleconstrange',['SimpleConstRange',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleConstRange.html',1,'DGtal']]],
  ['simpleincremental2x2detcomputer',['SimpleIncremental2x2DetComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleIncremental2x2DetComputer.html',1,'DGtal']]],
  ['simplelinearregression',['SimpleLinearRegression',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleLinearRegression.html',1,'DGtal']]],
  ['simplematrix',['SimpleMatrix',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleMatrix.html',1,'DGtal']]],
  ['simplematrix_3c_20double_2c_203_2c_203_20_3e',['SimpleMatrix&lt; double, 3, 3 &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleMatrix.html',1,'SimpleMatrix&lt; double, 3, 3 &gt;'],['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleMatrix.html',1,'DGtal::SimpleMatrix&lt; double, 3, 3 &gt;']]],
  ['simplematrix_3c_20integer_2c_203_2c_203_20_3e',['SimpleMatrix&lt; Integer, 3, 3 &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleMatrix.html',1,'SimpleMatrix&lt; Integer, 3, 3 &gt;'],['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleMatrix.html',1,'DGtal::SimpleMatrix&lt; Integer, 3, 3 &gt;']]],
  ['simplematrixspecializations',['SimpleMatrixSpecializations',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleMatrixSpecializations.html',1,'DGtal']]],
  ['simplematrixspecializations_3c_20tmatrix_2c_201_2c_201_20_3e',['SimpleMatrixSpecializations&lt; TMatrix, 1, 1 &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleMatrixSpecializations_3_01TMatrix_00_011_00_011_01_4.html',1,'DGtal']]],
  ['simplematrixspecializations_3c_20tmatrix_2c_202_2c_202_20_3e',['SimpleMatrixSpecializations&lt; TMatrix, 2, 2 &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleMatrixSpecializations_3_01TMatrix_00_012_00_012_01_4.html',1,'DGtal']]],
  ['simplematrixspecializations_3c_20tmatrix_2c_203_2c_203_20_3e',['SimpleMatrixSpecializations&lt; TMatrix, 3, 3 &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleMatrixSpecializations_3_01TMatrix_00_013_00_013_01_4.html',1,'DGtal']]],
  ['simplerandomaccessconstrangefrompoint',['SimpleRandomAccessConstRangeFromPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleRandomAccessConstRangeFromPoint.html',1,'DGtal']]],
  ['simplerandomaccessrangefrompoint',['SimpleRandomAccessRangeFromPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleRandomAccessRangeFromPoint.html',1,'DGtal']]],
  ['simplethresholdforegroundpredicate',['SimpleThresholdForegroundPredicate',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SimpleThresholdForegroundPredicate.html',1,'DGtal::functors']]],
  ['singlepassiteratorconcept',['SinglePassIteratorConcept',['https://dgtal-team.github.io/doc-nightly/structboost__concepts_1_1SinglePassIteratorConcept.html',1,'boost_concepts']]],
  ['slicerotator2d',['SliceRotator2D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SliceRotator2D.html',1,'DGtal::functors']]],
  ['sortedassociativecontainer',['SortedAssociativeContainer',['https://dgtal-team.github.io/doc-nightly/structboost_1_1SortedAssociativeContainer.html',1,'boost']]],
  ['spacend',['SpaceND',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpaceND.html',1,'DGtal']]],
  ['spacend_3c_202_2c_20integer_20_3e',['SpaceND&lt; 2, Integer &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpaceND.html',1,'DGtal::SpaceND&lt; 2, Integer &gt;'],['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpaceND.html',1,'SpaceND&lt; 2, Integer &gt;']]],
  ['spaniterator',['SpanIterator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1ImageContainerBySTLVector_1_1SpanIterator.html',1,'DGtal::ImageContainerBySTLVector']]],
  ['spatialcubicalsubdivision',['SpatialCubicalSubdivision',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpatialCubicalSubdivision.html',1,'DGtal']]],
  ['speedextrapolator',['SpeedExtrapolator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpeedExtrapolator.html',1,'DGtal']]],
  ['spherefittingestimator',['SphereFittingEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SphereFittingEstimator.html',1,'DGtal::functors']]],
  ['sphereshape',['SphereShape',['../structSphereShape.html',1,'']]],
  ['sphericalaccumulator',['SphericalAccumulator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SphericalAccumulator.html',1,'DGtal']]],
  ['sphericalaccumulator_3c_20dgtal_3a_3apointvector_20_3e',['SphericalAccumulator&lt; DGtal::PointVector &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SphericalAccumulator.html',1,'DGtal']]],
  ['sphericalaccumulator_3c_20realpoint_20_3e',['SphericalAccumulator&lt; RealPoint &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SphericalAccumulator.html',1,'']]],
  ['sphericalhoughnormalvectorestimator',['SphericalHoughNormalVectorEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SphericalHoughNormalVectorEstimator.html',1,'DGtal::functors']]],
  ['stabbingcirclecomputer',['StabbingCircleComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StabbingCircleComputer.html',1,'DGtal']]],
  ['stabbinglinecomputer',['StabbingLineComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StabbingLineComputer.html',1,'DGtal']]],
  ['standarddsl',['StandardDSL',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSL.html',1,'DGtal']]],
  ['standarddslq0',['StandardDSLQ0',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSLQ0.html',1,'DGtal']]],
  ['standarddss4',['StandardDSS4',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSS4.html',1,'DGtal']]],
  ['standarddss4computer',['StandardDSS4Computer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSS4Computer.html',1,'DGtal']]],
  ['standarddss6computer',['StandardDSS6Computer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSS6Computer.html',1,'DGtal']]],
  ['starshaped2d',['StarShaped2D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StarShaped2D.html',1,'DGtal']]],
  ['starshaped3d',['StarShaped3D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StarShaped3D.html',1,'DGtal']]],
  ['state',['State',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1UmbrellaComputer_1_1State.html',1,'DGtal::UmbrellaComputer::State'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1ChordNaivePlaneComputer_1_1State.html',1,'DGtal::ChordNaivePlaneComputer&lt; TSpace, TInputPoint, TInternalScalar &gt;::State'],['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1Board_1_1State.html',1,'LibBoard::Board::State'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1COBANaivePlaneComputer_1_1State.html',1,'DGtal::COBANaivePlaneComputer&lt; TSpace, TInternalInteger &gt;::State'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1AlphaThickSegmentComputer_1_1State.html',1,'DGtal::AlphaThickSegmentComputer&lt; TInputPoint, TConstIterator &gt;::State']]],
  ['statistic',['Statistic',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Statistic.html',1,'DGtal']]],
  ['statistic_3c_20value_20_3e',['Statistic&lt; Value &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Statistic.html',1,'DGtal::Statistic&lt; Value &gt;'],['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Statistic.html',1,'Statistic&lt; Value &gt;']]],
  ['stdmaprebinder',['StdMapRebinder',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1StdMapRebinder.html',1,'DGtal']]],
  ['sternbrocot',['SternBrocot',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SternBrocot.html',1,'DGtal']]],
  ['stlmaptovertexmapadapter',['STLMapToVertexMapAdapter',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1STLMapToVertexMapAdapter.html',1,'DGtal']]],
  ['straightlinefrom2points',['StraightLineFrom2Points',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StraightLineFrom2Points.html',1,'DGtal']]],
  ['stricttruncationfunctor',['StrictTruncationFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1StrictTruncationFunctor.html',1,'DGtal::functors']]],
  ['style2dfactory',['Style2DFactory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1Style2DFactory.html',1,'DGtal']]],
  ['subcospace',['Subcospace',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SpaceND_1_1Subcospace.html',1,'DGtal::SpaceND']]],
  ['subspace',['Subspace',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SpaceND_1_1Subspace.html',1,'DGtal::SpaceND']]],
  ['surfaces',['Surfaces',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Surfaces.html',1,'DGtal']]],
  ['surfeladjacency',['SurfelAdjacency',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelAdjacency.html',1,'DGtal']]],
  ['surfeladjacency_3c_20kspace_3a_3adimension_20_3e',['SurfelAdjacency&lt; KSpace::dimension &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelAdjacency.html',1,'DGtal::SurfelAdjacency&lt; KSpace::dimension &gt;'],['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelAdjacency.html',1,'SurfelAdjacency&lt; KSpace::dimension &gt;']]],
  ['surfelmap',['SurfelMap',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1KhalimskyPreSpaceND_1_1SurfelMap.html',1,'DGtal::KhalimskyPreSpaceND&lt; dim, TInteger &gt;::SurfelMap&lt; class &gt;'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1DigitalSurface_1_1SurfelMap.html',1,'DGtal::DigitalSurface&lt; TDigitalSurfaceContainer &gt;::SurfelMap&lt; Value &gt;'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1KhalimskySpaceND_1_1SurfelMap.html',1,'DGtal::KhalimskySpaceND&lt; dim, TInteger &gt;::SurfelMap&lt; class &gt;']]],
  ['surfelneighborhood',['SurfelNeighborhood',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelNeighborhood.html',1,'DGtal']]],
  ['surfelneighborhood_3c_20kspace_20_3e',['SurfelNeighborhood&lt; KSpace &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelNeighborhood.html',1,'SurfelNeighborhood&lt; KSpace &gt;'],['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelNeighborhood.html',1,'DGtal::SurfelNeighborhood&lt; KSpace &gt;']]],
  ['surfelsetpredicate',['SurfelSetPredicate',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1SurfelSetPredicate.html',1,'DGtal::functors']]],
  ['surfelsetpredicate_3c_20surfelset_2c_20surfel_20_3e',['SurfelSetPredicate&lt; SurfelSet, Surfel &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1SurfelSetPredicate.html',1,'DGtal::functors::SurfelSetPredicate&lt; SurfelSet, Surfel &gt;'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1SurfelSetPredicate.html',1,'SurfelSetPredicate&lt; SurfelSet, Surfel &gt;']]],
  ['swappableiteratorconcept',['SwappableIteratorConcept',['https://dgtal-team.github.io/doc-nightly/structboost__concepts_1_1SwappableIteratorConcept.html',1,'boost_concepts']]]
];
