var searchData=
[
  ['sametype_0',['SameType',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1concepts_1_1ConceptUtils_1_1SameType.html',1,'DGtal::concepts::ConceptUtils']]],
  ['sametype_3c_20t_2c_20t_20_3e_1',['SameType&lt; T, T &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1concepts_1_1ConceptUtils_1_1SameType_3_01T_00_01T_01_4.html',1,'DGtal::concepts::ConceptUtils']]],
  ['saturatedsegmentation_2',['SaturatedSegmentation',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SaturatedSegmentation.html',1,'DGtal']]],
  ['scellmap_3',['scellmap',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1KhalimskyPreSpaceND_1_1SCellMap.html',1,'DGtal::KhalimskyPreSpaceND::SCellMap&lt; class &gt;'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1KhalimskySpaceND_1_1SCellMap.html',1,'DGtal::KhalimskySpaceND::SCellMap&lt; class &gt;']]],
  ['scelltoarrow_4',['SCellToArrow',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToArrow.html',1,'DGtal::functors']]],
  ['scelltocode_5',['SCellToCode',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToCode.html',1,'DGtal::functors']]],
  ['scelltoincidentpoints_6',['SCellToIncidentPoints',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToIncidentPoints.html',1,'DGtal::functors']]],
  ['scelltoinnerpoint_7',['SCellToInnerPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToInnerPoint.html',1,'DGtal::functors']]],
  ['scelltomidpoint_8',['SCellToMidPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1deprecated_1_1SCellToMidPoint.html',1,'DGtal::functors::deprecated']]],
  ['scelltoouterpoint_9',['SCellToOuterPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToOuterPoint.html',1,'DGtal::functors']]],
  ['scelltopoint_10',['SCellToPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToPoint.html',1,'DGtal::functors']]],
  ['segmentcomputeriterator_11',['segmentcomputeriterator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1GreedySegmentation_1_1SegmentComputerIterator.html',1,'DGtal::GreedySegmentation&lt; TSegmentComputer &gt;::SegmentComputerIterator'],['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SaturatedSegmentation_1_1SegmentComputerIterator.html',1,'DGtal::SaturatedSegmentation&lt; TSegmentComputer &gt;::SegmentComputerIterator']]],
  ['segmentcomputertraits_12',['SegmentComputerTraits',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SegmentComputerTraits.html',1,'DGtal']]],
  ['selectcallbackfctstore_13',['SelectCallbackFctStore',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1Display3D_1_1SelectCallbackFctStore.html',1,'DGtal::Display3D']]],
  ['separablemetricadapter_14',['SeparableMetricAdapter',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SeparableMetricAdapter.html',1,'DGtal']]],
  ['sequence_15',['Sequence',['https://dgtal-team.github.io/doc-nightly/structboost_1_1Sequence.html',1,'boost']]],
  ['sequencecategory_16',['SequenceCategory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SequenceCategory.html',1,'DGtal']]],
  ['setassociativecategory_17',['SetAssociativeCategory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetAssociativeCategory.html',1,'DGtal']]],
  ['setfromimage_18',['SetFromImage',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetFromImage.html',1,'DGtal']]],
  ['setfunctionsimpl_19',['SetFunctionsImpl',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1SetFunctionsImpl.html',1,'DGtal::detail']]],
  ['setfunctionsimpl_3c_20container_2c_20false_2c_20true_20_3e_20',['SetFunctionsImpl&lt; Container, false, true &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1SetFunctionsImpl_3_01Container_00_01false_00_01true_01_4.html',1,'DGtal::detail']]],
  ['setfunctionsimpl_3c_20container_2c_20true_2c_20false_20_3e_21',['SetFunctionsImpl&lt; Container, true, false &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1SetFunctionsImpl_3_01Container_00_01true_00_01false_01_4.html',1,'DGtal::detail']]],
  ['setfunctionsimpl_3c_20container_2c_20true_2c_20true_20_3e_22',['SetFunctionsImpl&lt; Container, true, true &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1SetFunctionsImpl_3_01Container_00_01true_00_01true_01_4.html',1,'DGtal::detail']]],
  ['setmode_23',['SetMode',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetMode.html',1,'DGtal']]],
  ['setmode3d_24',['SetMode3D',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetMode3D.html',1,'DGtal']]],
  ['setname3d_25',['SetName3D',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetName3D.html',1,'DGtal']]],
  ['setofsurfels_26',['SetOfSurfels',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SetOfSurfels.html',1,'DGtal']]],
  ['setpredicate_27',['SetPredicate',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1deprecated_1_1SetPredicate.html',1,'DGtal::deprecated']]],
  ['setselectcallback3d_28',['SetSelectCallback3D',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetSelectCallback3D.html',1,'DGtal']]],
  ['setvalueiterator_29',['SetValueIterator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SetValueIterator.html',1,'DGtal']]],
  ['sgiassignable_30',['SGIAssignable',['https://dgtal-team.github.io/doc-nightly/structboost_1_1SGIAssignable.html',1,'boost']]],
  ['shape_31',['Shape',['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1Shape.html',1,'LibBoard']]],
  ['shapelist_32',['ShapeList',['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1ShapeList.html',1,'LibBoard']]],
  ['shapemeancurvaturefunctor_33',['ShapeMeanCurvatureFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeMeanCurvatureFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapenormalvectorfunctor_34',['ShapeNormalVectorFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeNormalVectorFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapepositionfunctor_35',['ShapePositionFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapePositionFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapes_36',['Shapes',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Shapes.html',1,'DGtal']]],
  ['signal_37',['Signal',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Signal.html',1,'DGtal']]],
  ['signal_3c_20value_20_3e_38',['Signal&lt; Value &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Signal.html',1,'']]],
  ['signaldata_39',['SignalData',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignalData.html',1,'DGtal']]],
  ['signedinteger_40',['SignedInteger',['https://dgtal-team.github.io/doc-nightly/structboost_1_1SignedInteger.html',1,'boost']]],
  ['signedkhalimskycell_41',['SignedKhalimskyCell',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignedKhalimskyCell.html',1,'DGtal']]],
  ['signedkhalimskyprecell_42',['SignedKhalimskyPreCell',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignedKhalimskyPreCell.html',1,'DGtal']]],
  ['signedkhalimskyprecell_3c_20dim_2c_20integer_20_3e_43',['SignedKhalimskyPreCell&lt; dim, Integer &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignedKhalimskyPreCell.html',1,'']]],
  ['simple2x2detcomputer_44',['Simple2x2DetComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Simple2x2DetComputer.html',1,'DGtal']]],
  ['simple2x2detcomputer_3c_20integer_20_3e_45',['Simple2x2DetComputer&lt; Integer &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Simple2x2DetComputer.html',1,'']]],
  ['simpleassociativecategory_46',['SimpleAssociativeCategory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleAssociativeCategory.html',1,'DGtal']]],
  ['simpleassociativecontainer_47',['SimpleAssociativeContainer',['https://dgtal-team.github.io/doc-nightly/structboost_1_1SimpleAssociativeContainer.html',1,'boost']]],
  ['simpleconstrange_48',['SimpleConstRange',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleConstRange.html',1,'DGtal']]],
  ['simpleincremental2x2detcomputer_49',['SimpleIncremental2x2DetComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleIncremental2x2DetComputer.html',1,'DGtal']]],
  ['simplelinearregression_50',['SimpleLinearRegression',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleLinearRegression.html',1,'DGtal']]],
  ['simplematrix_51',['SimpleMatrix',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleMatrix.html',1,'DGtal']]],
  ['simplematrix_3c_20double_2c_203_2c_203_20_3e_52',['SimpleMatrix&lt; double, 3, 3 &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleMatrix.html',1,'']]],
  ['simplematrix_3c_20integer_2c_203_2c_203_20_3e_53',['SimpleMatrix&lt; Integer, 3, 3 &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleMatrix.html',1,'']]],
  ['simplematrixspecializations_54',['SimpleMatrixSpecializations',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleMatrixSpecializations.html',1,'DGtal']]],
  ['simplematrixspecializations_3c_20tmatrix_2c_201_2c_201_20_3e_55',['SimpleMatrixSpecializations&lt; TMatrix, 1, 1 &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleMatrixSpecializations_3_01TMatrix_00_011_00_011_01_4.html',1,'DGtal']]],
  ['simplematrixspecializations_3c_20tmatrix_2c_202_2c_202_20_3e_56',['SimpleMatrixSpecializations&lt; TMatrix, 2, 2 &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleMatrixSpecializations_3_01TMatrix_00_012_00_012_01_4.html',1,'DGtal']]],
  ['simplematrixspecializations_3c_20tmatrix_2c_203_2c_203_20_3e_57',['SimpleMatrixSpecializations&lt; TMatrix, 3, 3 &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleMatrixSpecializations_3_01TMatrix_00_013_00_013_01_4.html',1,'DGtal']]],
  ['simplerandomaccessconstrangefrompoint_58',['SimpleRandomAccessConstRangeFromPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleRandomAccessConstRangeFromPoint.html',1,'DGtal']]],
  ['simplerandomaccessrangefrompoint_59',['SimpleRandomAccessRangeFromPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleRandomAccessRangeFromPoint.html',1,'DGtal']]],
  ['simplethresholdforegroundpredicate_60',['SimpleThresholdForegroundPredicate',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SimpleThresholdForegroundPredicate.html',1,'DGtal::functors']]],
  ['singlepassiteratorconcept_61',['SinglePassIteratorConcept',['https://dgtal-team.github.io/doc-nightly/structboost__concepts_1_1SinglePassIteratorConcept.html',1,'boost_concepts']]],
  ['slicerotator2d_62',['SliceRotator2D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SliceRotator2D.html',1,'DGtal::functors']]],
  ['sortedassociativecontainer_63',['SortedAssociativeContainer',['https://dgtal-team.github.io/doc-nightly/structboost_1_1SortedAssociativeContainer.html',1,'boost']]],
  ['spacend_64',['SpaceND',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpaceND.html',1,'DGtal']]],
  ['spacend_3c_202_2c_20integer_20_3e_65',['SpaceND&lt; 2, Integer &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpaceND.html',1,'']]],
  ['spaniterator_66',['SpanIterator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1ImageContainerBySTLVector_1_1SpanIterator.html',1,'DGtal::ImageContainerBySTLVector']]],
  ['spatialcubicalsubdivision_67',['SpatialCubicalSubdivision',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpatialCubicalSubdivision.html',1,'DGtal']]],
  ['speedextrapolator_68',['SpeedExtrapolator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpeedExtrapolator.html',1,'DGtal']]],
  ['spherefittingestimator_69',['SphereFittingEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SphereFittingEstimator.html',1,'DGtal::functors']]],
  ['sphereshape_70',['SphereShape',['../structSphereShape.html',1,'']]],
  ['sphericalaccumulator_71',['SphericalAccumulator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SphericalAccumulator.html',1,'DGtal']]],
  ['sphericalaccumulator_3c_20dgtal_3a_3apointvector_20_3e_72',['SphericalAccumulator&lt; DGtal::PointVector &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SphericalAccumulator.html',1,'DGtal']]],
  ['sphericalaccumulator_3c_20realpoint_20_3e_73',['SphericalAccumulator&lt; RealPoint &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SphericalAccumulator.html',1,'']]],
  ['sphericalhoughnormalvectorestimator_74',['SphericalHoughNormalVectorEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SphericalHoughNormalVectorEstimator.html',1,'DGtal::functors']]],
  ['stabbingcirclecomputer_75',['StabbingCircleComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StabbingCircleComputer.html',1,'DGtal']]],
  ['stabbinglinecomputer_76',['StabbingLineComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StabbingLineComputer.html',1,'DGtal']]],
  ['standarddsl_77',['StandardDSL',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSL.html',1,'DGtal']]],
  ['standarddslq0_78',['StandardDSLQ0',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSLQ0.html',1,'DGtal']]],
  ['standarddss4_79',['StandardDSS4',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSS4.html',1,'DGtal']]],
  ['standarddss4computer_80',['StandardDSS4Computer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSS4Computer.html',1,'DGtal']]],
  ['standarddss6computer_81',['StandardDSS6Computer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSS6Computer.html',1,'DGtal']]],
  ['starshaped2d_82',['StarShaped2D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StarShaped2D.html',1,'DGtal']]],
  ['starshaped3d_83',['StarShaped3D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StarShaped3D.html',1,'DGtal']]],
  ['state_84',['state',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1AlphaThickSegmentComputer_1_1State.html',1,'DGtal::AlphaThickSegmentComputer&lt; TInputPoint, TConstIterator &gt;::State'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1ChordNaivePlaneComputer_1_1State.html',1,'DGtal::ChordNaivePlaneComputer&lt; TSpace, TInputPoint, TInternalScalar &gt;::State'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1COBANaivePlaneComputer_1_1State.html',1,'DGtal::COBANaivePlaneComputer&lt; TSpace, TInternalInteger &gt;::State'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1UmbrellaComputer_1_1State.html',1,'DGtal::UmbrellaComputer::State'],['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1Board_1_1State.html',1,'LibBoard::Board::State']]],
  ['statistic_85',['Statistic',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Statistic.html',1,'DGtal']]],
  ['statistic_3c_20value_20_3e_86',['Statistic&lt; Value &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Statistic.html',1,'']]],
  ['stdmaprebinder_87',['StdMapRebinder',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1StdMapRebinder.html',1,'DGtal']]],
  ['sternbrocot_88',['SternBrocot',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SternBrocot.html',1,'DGtal']]],
  ['stlmaptovertexmapadapter_89',['STLMapToVertexMapAdapter',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1STLMapToVertexMapAdapter.html',1,'DGtal']]],
  ['straightlinefrom2points_90',['StraightLineFrom2Points',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StraightLineFrom2Points.html',1,'DGtal']]],
  ['stricttruncationfunctor_91',['StrictTruncationFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1StrictTruncationFunctor.html',1,'DGtal::functors']]],
  ['style2dfactory_92',['Style2DFactory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1Style2DFactory.html',1,'DGtal']]],
  ['subcospace_93',['Subcospace',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SpaceND_1_1Subcospace.html',1,'DGtal::SpaceND']]],
  ['subspace_94',['Subspace',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SpaceND_1_1Subspace.html',1,'DGtal::SpaceND']]],
  ['surfaces_95',['Surfaces',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Surfaces.html',1,'DGtal']]],
  ['surfeladjacency_96',['SurfelAdjacency',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelAdjacency.html',1,'DGtal']]],
  ['surfeladjacency_3c_20kspace_3a_3adimension_20_3e_97',['SurfelAdjacency&lt; KSpace::dimension &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelAdjacency.html',1,'']]],
  ['surfelmap_98',['surfelmap',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1DigitalSurface_1_1SurfelMap.html',1,'DGtal::DigitalSurface::SurfelMap&lt; Value &gt;'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1KhalimskyPreSpaceND_1_1SurfelMap.html',1,'DGtal::KhalimskyPreSpaceND::SurfelMap&lt; class &gt;'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1KhalimskySpaceND_1_1SurfelMap.html',1,'DGtal::KhalimskySpaceND::SurfelMap&lt; class &gt;']]],
  ['surfelneighborhood_99',['SurfelNeighborhood',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelNeighborhood.html',1,'DGtal']]],
  ['surfelneighborhood_3c_20kspace_20_3e_100',['SurfelNeighborhood&lt; KSpace &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelNeighborhood.html',1,'']]],
  ['surfelsetpredicate_101',['SurfelSetPredicate',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1SurfelSetPredicate.html',1,'DGtal::functors']]],
  ['surfelsetpredicate_3c_20surfelset_2c_20surfel_20_3e_102',['SurfelSetPredicate&lt; SurfelSet, Surfel &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1SurfelSetPredicate.html',1,'']]],
  ['swappableiteratorconcept_103',['SwappableIteratorConcept',['https://dgtal-team.github.io/doc-nightly/structboost__concepts_1_1SwappableIteratorConcept.html',1,'boost_concepts']]]
];
