var searchData=
[
  ['l1lengthestimator_6396',['L1LengthEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1L1LengthEstimator.html',1,'DGtal']]],
  ['l1localdistance_6397',['L1LocalDistance',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1L1LocalDistance.html',1,'DGtal']]],
  ['l2firstorderlocaldistance_6398',['L2FirstOrderLocalDistance',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1L2FirstOrderLocalDistance.html',1,'DGtal']]],
  ['l2firstorderlocaldistancefromcells_6399',['L2FirstOrderLocalDistanceFromCells',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1L2FirstOrderLocalDistanceFromCells.html',1,'DGtal']]],
  ['l2secondorderlocaldistance_6400',['L2SecondOrderLocalDistance',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1L2SecondOrderLocalDistance.html',1,'DGtal']]],
  ['labelledmap_6401',['LabelledMap',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LabelledMap.html',1,'DGtal']]],
  ['labelledmap_3c_20value_2c_20l_2c_20tword_2c_20n_2c_20m_20_3e_6402',['LabelledMap&lt; Value, L, TWord, N, M &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LabelledMap.html',1,'']]],
  ['labelledmapmemfunctor_6403',['LabelledMapMemFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1LabelledMapMemFunctor.html',1,'DGtal::detail']]],
  ['labels_6404',['Labels',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Labels.html',1,'DGtal']]],
  ['labels_3c_20l_2c_20word_20_3e_6405',['Labels&lt; L, Word &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Labels.html',1,'']]],
  ['lambda64function_6406',['Lambda64Function',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1Lambda64Function.html',1,'DGtal::functors']]],
  ['lambdaexponentialfunction_6407',['LambdaExponentialFunction',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1LambdaExponentialFunction.html',1,'DGtal::functors']]],
  ['lambdamst2d_6408',['LambdaMST2D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LambdaMST2D.html',1,'DGtal']]],
  ['lambdamst2destimator_6409',['LambdaMST2DEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LambdaMST2DEstimator.html',1,'DGtal']]],
  ['lambdamst2destimator_3c_20z2i_3a_3aspace_2c_20dsssegmentationcomputer_2c_20tangentfromdss2dfunctor_3c_20dsssegmentationcomputer_3a_3asegmentcomputer_2c_20lambdafunction_20_3e_20_3e_6410',['LambdaMST2DEstimator&lt; Z2i::Space, DSSSegmentationComputer, TangentFromDSS2DFunctor&lt; DSSSegmentationComputer::SegmentComputer, LambdaFunction &gt; &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LambdaMST2DEstimator.html',1,'']]],
  ['lambdamst3d_6411',['LambdaMST3D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LambdaMST3D.html',1,'DGtal']]],
  ['lambdamst3destimator_6412',['LambdaMST3DEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LambdaMST3DEstimator.html',1,'DGtal']]],
  ['lambdamst3destimator_3c_20z3i_3a_3aspace_2c_20dsssegmentationcomputer_2c_20tangentfromdss3dfunctor_3c_20dsssegmentationcomputer_3a_3asegmentcomputer_2c_20lambdafunction_20_3e_20_3e_6413',['LambdaMST3DEstimator&lt; Z3i::Space, DSSSegmentationComputer, TangentFromDSS3DFunctor&lt; DSSSegmentationComputer::SegmentComputer, LambdaFunction &gt; &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LambdaMST3DEstimator.html',1,'']]],
  ['lambdasinfrompifunction_6414',['LambdaSinFromPiFunction',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1LambdaSinFromPiFunction.html',1,'DGtal::functors']]],
  ['largetruncationfunctor_6415',['LargeTruncationFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1LargeTruncationFunctor.html',1,'DGtal::functors']]],
  ['latticepolytope2d_6416',['LatticePolytope2D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LatticePolytope2D.html',1,'DGtal']]],
  ['latticepolytope2d_3c_20internalspace2_20_3e_6417',['LatticePolytope2D&lt; InternalSpace2 &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LatticePolytope2D.html',1,'']]],
  ['lessoreqthanangular_6418',['LessOrEqThanAngular',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1experimental_1_1ChamferNorm2D_1_1LessOrEqThanAngular.html',1,'DGtal::experimental::ChamferNorm2D']]],
  ['lessthanangular_6419',['LessThanAngular',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1experimental_1_1ChamferNorm2D_1_1LessThanAngular.html',1,'DGtal::experimental::ChamferNorm2D']]],
  ['lessthancomparable_6420',['LessThanComparable',['https://dgtal-team.github.io/doc-nightly/structboost_1_1LessThanComparable.html',1,'boost']]],
  ['lightersternbrocot_6421',['LighterSternBrocot',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LighterSternBrocot.html',1,'DGtal']]],
  ['lightexplicitdigitalsurface_6422',['LightExplicitDigitalSurface',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LightExplicitDigitalSurface.html',1,'DGtal']]],
  ['lightimplicitdigitalsurface_6423',['LightImplicitDigitalSurface',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LightImplicitDigitalSurface.html',1,'DGtal']]],
  ['lightsternbrocot_6424',['LightSternBrocot',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LightSternBrocot.html',1,'DGtal']]],
  ['line_6425',['Line',['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1Line.html',1,'LibBoard']]],
  ['linearalgebra_6426',['LinearAlgebra',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1LinearAlgebra.html',1,'DGtal']]],
  ['linearizer_6427',['Linearizer',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1Linearizer.html',1,'DGtal']]],
  ['linearizer_3c_20hyperrectdomain_3c_20tspace_20_3e_2c_20tstorageorder_20_3e_6428',['Linearizer&lt; HyperRectDomain&lt; TSpace &gt;, TStorageOrder &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1Linearizer_3_01HyperRectDomain_3_01TSpace_01_4_00_01TStorageOrder_01_4.html',1,'DGtal']]],
  ['linearleastsquarefittingnormalvectorestimator_6429',['LinearLeastSquareFittingNormalVectorEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1LinearLeastSquareFittingNormalVectorEstimator.html',1,'DGtal::functors']]],
  ['linearoperator_6430',['LinearOperator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LinearOperator.html',1,'DGtal']]],
  ['lined3d_6431',['LineD3D',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1Display3D_1_1LineD3D.html',1,'DGtal::Display3D']]],
  ['linflocaldistance_6432',['LInfLocalDistance',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LInfLocalDistance.html',1,'DGtal']]],
  ['localconvolutionnormalvectorestimator_6433',['LocalConvolutionNormalVectorEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1deprecated_1_1LocalConvolutionNormalVectorEstimator.html',1,'DGtal::deprecated']]],
  ['localestimatorfromsurfelfunctoradapter_6434',['LocalEstimatorFromSurfelFunctorAdapter',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LocalEstimatorFromSurfelFunctorAdapter.html',1,'DGtal']]],
  ['log2_6435',['LOG2',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LOG2.html',1,'DGtal']]],
  ['log2_3c_201_20_3e_6436',['LOG2&lt; 1 &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LOG2_3_011_01_4.html',1,'DGtal']]],
  ['log2_3c_202_20_3e_6437',['LOG2&lt; 2 &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1LOG2_3_012_01_4.html',1,'DGtal']]],
  ['longvolreader_6438',['LongvolReader',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1LongvolReader.html',1,'DGtal']]],
  ['longvolwriter_6439',['LongvolWriter',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1LongvolWriter.html',1,'DGtal']]],
  ['lvalueiteratorconcept_6440',['LvalueIteratorConcept',['https://dgtal-team.github.io/doc-nightly/structboost__concepts_1_1LvalueIteratorConcept.html',1,'boost_concepts']]]
];
