var searchData=
[
  ['sametype_6657',['SameType',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1concepts_1_1ConceptUtils_1_1SameType.html',1,'DGtal::concepts::ConceptUtils']]],
  ['sametype_3c_20t_2c_20t_20_3e_6658',['SameType&lt; T, T &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1concepts_1_1ConceptUtils_1_1SameType_3_01T_00_01T_01_4.html',1,'DGtal::concepts::ConceptUtils']]],
  ['saturatedsegmentation_6659',['SaturatedSegmentation',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SaturatedSegmentation.html',1,'DGtal']]],
  ['scellmap_6660',['SCellMap',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1KhalimskyPreSpaceND_1_1SCellMap.html',1,'DGtal::KhalimskyPreSpaceND&lt; dim, TInteger &gt;::SCellMap&lt; class &gt;'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1KhalimskySpaceND_1_1SCellMap.html',1,'DGtal::KhalimskySpaceND&lt; dim, TInteger &gt;::SCellMap&lt; class &gt;']]],
  ['scelltoarrow_6661',['SCellToArrow',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToArrow.html',1,'DGtal::functors']]],
  ['scelltocode_6662',['SCellToCode',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToCode.html',1,'DGtal::functors']]],
  ['scelltoincidentpoints_6663',['SCellToIncidentPoints',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToIncidentPoints.html',1,'DGtal::functors']]],
  ['scelltoinnerpoint_6664',['SCellToInnerPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToInnerPoint.html',1,'DGtal::functors']]],
  ['scelltomidpoint_6665',['SCellToMidPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1deprecated_1_1SCellToMidPoint.html',1,'DGtal::functors::deprecated']]],
  ['scelltoouterpoint_6666',['SCellToOuterPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToOuterPoint.html',1,'DGtal::functors']]],
  ['scelltopoint_6667',['SCellToPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SCellToPoint.html',1,'DGtal::functors']]],
  ['segmentcomputeriterator_6668',['SegmentComputerIterator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1GreedySegmentation_1_1SegmentComputerIterator.html',1,'DGtal::GreedySegmentation&lt; TSegmentComputer &gt;::SegmentComputerIterator'],['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SaturatedSegmentation_1_1SegmentComputerIterator.html',1,'DGtal::SaturatedSegmentation&lt; TSegmentComputer &gt;::SegmentComputerIterator']]],
  ['segmentcomputertraits_6669',['SegmentComputerTraits',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SegmentComputerTraits.html',1,'DGtal']]],
  ['selectcallbackfctstore_6670',['SelectCallbackFctStore',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1Display3D_1_1SelectCallbackFctStore.html',1,'DGtal::Display3D']]],
  ['separablemetricadapter_6671',['SeparableMetricAdapter',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SeparableMetricAdapter.html',1,'DGtal']]],
  ['sequence_6672',['Sequence',['https://dgtal-team.github.io/doc-nightly/structboost_1_1Sequence.html',1,'boost']]],
  ['sequencecategory_6673',['SequenceCategory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SequenceCategory.html',1,'DGtal']]],
  ['setassociativecategory_6674',['SetAssociativeCategory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetAssociativeCategory.html',1,'DGtal']]],
  ['setfromimage_6675',['SetFromImage',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetFromImage.html',1,'DGtal']]],
  ['setfunctionsimpl_6676',['SetFunctionsImpl',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1SetFunctionsImpl.html',1,'DGtal::detail']]],
  ['setfunctionsimpl_3c_20container_2c_20false_2c_20true_20_3e_6677',['SetFunctionsImpl&lt; Container, false, true &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1SetFunctionsImpl_3_01Container_00_01false_00_01true_01_4.html',1,'DGtal::detail']]],
  ['setfunctionsimpl_3c_20container_2c_20true_2c_20false_20_3e_6678',['SetFunctionsImpl&lt; Container, true, false &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1SetFunctionsImpl_3_01Container_00_01true_00_01false_01_4.html',1,'DGtal::detail']]],
  ['setfunctionsimpl_3c_20container_2c_20true_2c_20true_20_3e_6679',['SetFunctionsImpl&lt; Container, true, true &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1SetFunctionsImpl_3_01Container_00_01true_00_01true_01_4.html',1,'DGtal::detail']]],
  ['setmode_6680',['SetMode',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetMode.html',1,'DGtal']]],
  ['setmode3d_6681',['SetMode3D',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetMode3D.html',1,'DGtal']]],
  ['setname3d_6682',['SetName3D',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetName3D.html',1,'DGtal']]],
  ['setofsurfels_6683',['SetOfSurfels',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SetOfSurfels.html',1,'DGtal']]],
  ['setpredicate_6684',['SetPredicate',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1deprecated_1_1SetPredicate.html',1,'DGtal::deprecated']]],
  ['setselectcallback3d_6685',['SetSelectCallback3D',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SetSelectCallback3D.html',1,'DGtal']]],
  ['setvalueiterator_6686',['SetValueIterator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SetValueIterator.html',1,'DGtal']]],
  ['sgiassignable_6687',['SGIAssignable',['https://dgtal-team.github.io/doc-nightly/structboost_1_1SGIAssignable.html',1,'boost']]],
  ['shape_6688',['Shape',['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1Shape.html',1,'LibBoard']]],
  ['shapelist_6689',['ShapeList',['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1ShapeList.html',1,'LibBoard']]],
  ['shapemeancurvaturefunctor_6690',['ShapeMeanCurvatureFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeMeanCurvatureFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapenormalvectorfunctor_6691',['ShapeNormalVectorFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeNormalVectorFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapepositionfunctor_6692',['ShapePositionFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapePositionFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapes_6693',['Shapes',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Shapes.html',1,'DGtal']]],
  ['signal_6694',['Signal',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Signal.html',1,'DGtal']]],
  ['signal_3c_20value_20_3e_6695',['Signal&lt; Value &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Signal.html',1,'']]],
  ['signaldata_6696',['SignalData',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignalData.html',1,'DGtal']]],
  ['signedinteger_6697',['SignedInteger',['https://dgtal-team.github.io/doc-nightly/structboost_1_1SignedInteger.html',1,'boost']]],
  ['signedkhalimskycell_6698',['SignedKhalimskyCell',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignedKhalimskyCell.html',1,'DGtal']]],
  ['signedkhalimskyprecell_6699',['SignedKhalimskyPreCell',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignedKhalimskyPreCell.html',1,'DGtal']]],
  ['signedkhalimskyprecell_3c_20dim_2c_20integer_20_3e_6700',['SignedKhalimskyPreCell&lt; dim, Integer &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SignedKhalimskyPreCell.html',1,'']]],
  ['simple2x2detcomputer_6701',['Simple2x2DetComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Simple2x2DetComputer.html',1,'DGtal']]],
  ['simple2x2detcomputer_3c_20integer_20_3e_6702',['Simple2x2DetComputer&lt; Integer &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Simple2x2DetComputer.html',1,'']]],
  ['simpleassociativecategory_6703',['SimpleAssociativeCategory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleAssociativeCategory.html',1,'DGtal']]],
  ['simpleassociativecontainer_6704',['SimpleAssociativeContainer',['https://dgtal-team.github.io/doc-nightly/structboost_1_1SimpleAssociativeContainer.html',1,'boost']]],
  ['simpleconstrange_6705',['SimpleConstRange',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleConstRange.html',1,'DGtal']]],
  ['simpleincremental2x2detcomputer_6706',['SimpleIncremental2x2DetComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleIncremental2x2DetComputer.html',1,'DGtal']]],
  ['simplelinearregression_6707',['SimpleLinearRegression',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleLinearRegression.html',1,'DGtal']]],
  ['simplematrix_6708',['SimpleMatrix',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleMatrix.html',1,'DGtal']]],
  ['simplematrix_3c_20double_2c_203_2c_203_20_3e_6709',['SimpleMatrix&lt; double, 3, 3 &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleMatrix.html',1,'']]],
  ['simplematrix_3c_20integer_2c_203_2c_203_20_3e_6710',['SimpleMatrix&lt; Integer, 3, 3 &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleMatrix.html',1,'']]],
  ['simplematrixspecializations_6711',['SimpleMatrixSpecializations',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleMatrixSpecializations.html',1,'DGtal']]],
  ['simplematrixspecializations_3c_20tmatrix_2c_201_2c_201_20_3e_6712',['SimpleMatrixSpecializations&lt; TMatrix, 1, 1 &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleMatrixSpecializations_3_01TMatrix_00_011_00_011_01_4.html',1,'DGtal']]],
  ['simplematrixspecializations_3c_20tmatrix_2c_202_2c_202_20_3e_6713',['SimpleMatrixSpecializations&lt; TMatrix, 2, 2 &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleMatrixSpecializations_3_01TMatrix_00_012_00_012_01_4.html',1,'DGtal']]],
  ['simplematrixspecializations_3c_20tmatrix_2c_203_2c_203_20_3e_6714',['SimpleMatrixSpecializations&lt; TMatrix, 3, 3 &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SimpleMatrixSpecializations_3_01TMatrix_00_013_00_013_01_4.html',1,'DGtal']]],
  ['simplerandomaccessconstrangefrompoint_6715',['SimpleRandomAccessConstRangeFromPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleRandomAccessConstRangeFromPoint.html',1,'DGtal']]],
  ['simplerandomaccessrangefrompoint_6716',['SimpleRandomAccessRangeFromPoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SimpleRandomAccessRangeFromPoint.html',1,'DGtal']]],
  ['simplethresholdforegroundpredicate_6717',['SimpleThresholdForegroundPredicate',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SimpleThresholdForegroundPredicate.html',1,'DGtal::functors']]],
  ['singlepassiteratorconcept_6718',['SinglePassIteratorConcept',['https://dgtal-team.github.io/doc-nightly/structboost__concepts_1_1SinglePassIteratorConcept.html',1,'boost_concepts']]],
  ['slicerotator2d_6719',['SliceRotator2D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SliceRotator2D.html',1,'DGtal::functors']]],
  ['sortedassociativecontainer_6720',['SortedAssociativeContainer',['https://dgtal-team.github.io/doc-nightly/structboost_1_1SortedAssociativeContainer.html',1,'boost']]],
  ['spacend_6721',['SpaceND',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpaceND.html',1,'DGtal']]],
  ['spacend_3c_202_2c_20integer_20_3e_6722',['SpaceND&lt; 2, Integer &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpaceND.html',1,'']]],
  ['spaniterator_6723',['SpanIterator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1ImageContainerBySTLVector_1_1SpanIterator.html',1,'DGtal::ImageContainerBySTLVector']]],
  ['spatialcubicalsubdivision_6724',['SpatialCubicalSubdivision',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpatialCubicalSubdivision.html',1,'DGtal']]],
  ['speedextrapolator_6725',['SpeedExtrapolator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SpeedExtrapolator.html',1,'DGtal']]],
  ['spherefittingestimator_6726',['SphereFittingEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SphereFittingEstimator.html',1,'DGtal::functors']]],
  ['sphereshape_6727',['SphereShape',['../structSphereShape.html',1,'']]],
  ['sphericalaccumulator_6728',['SphericalAccumulator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SphericalAccumulator.html',1,'DGtal']]],
  ['sphericalaccumulator_3c_20dgtal_3a_3apointvector_20_3e_6729',['SphericalAccumulator&lt; DGtal::PointVector &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SphericalAccumulator.html',1,'DGtal']]],
  ['sphericalaccumulator_3c_20realpoint_20_3e_6730',['SphericalAccumulator&lt; RealPoint &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SphericalAccumulator.html',1,'']]],
  ['sphericalhoughnormalvectorestimator_6731',['SphericalHoughNormalVectorEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SphericalHoughNormalVectorEstimator.html',1,'DGtal::functors']]],
  ['stabbingcirclecomputer_6732',['StabbingCircleComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StabbingCircleComputer.html',1,'DGtal']]],
  ['stabbinglinecomputer_6733',['StabbingLineComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StabbingLineComputer.html',1,'DGtal']]],
  ['standarddsl_6734',['StandardDSL',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSL.html',1,'DGtal']]],
  ['standarddslq0_6735',['StandardDSLQ0',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSLQ0.html',1,'DGtal']]],
  ['standarddss4_6736',['StandardDSS4',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSS4.html',1,'DGtal']]],
  ['standarddss4computer_6737',['StandardDSS4Computer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSS4Computer.html',1,'DGtal']]],
  ['standarddss6computer_6738',['StandardDSS6Computer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StandardDSS6Computer.html',1,'DGtal']]],
  ['starshaped2d_6739',['StarShaped2D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StarShaped2D.html',1,'DGtal']]],
  ['starshaped3d_6740',['StarShaped3D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StarShaped3D.html',1,'DGtal']]],
  ['state_6741',['State',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1AlphaThickSegmentComputer_1_1State.html',1,'DGtal::AlphaThickSegmentComputer&lt; TInputPoint, TConstIterator &gt;::State'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1ChordNaivePlaneComputer_1_1State.html',1,'DGtal::ChordNaivePlaneComputer&lt; TSpace, TInputPoint, TInternalScalar &gt;::State'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1COBANaivePlaneComputer_1_1State.html',1,'DGtal::COBANaivePlaneComputer&lt; TSpace, TInternalInteger &gt;::State'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1UmbrellaComputer_1_1State.html',1,'DGtal::UmbrellaComputer::State'],['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1Board_1_1State.html',1,'LibBoard::Board::State']]],
  ['statistic_6742',['Statistic',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Statistic.html',1,'DGtal']]],
  ['statistic_3c_20value_20_3e_6743',['Statistic&lt; Value &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Statistic.html',1,'']]],
  ['stdmaprebinder_6744',['StdMapRebinder',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1StdMapRebinder.html',1,'DGtal']]],
  ['sternbrocot_6745',['SternBrocot',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SternBrocot.html',1,'DGtal']]],
  ['stlmaptovertexmapadapter_6746',['STLMapToVertexMapAdapter',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1STLMapToVertexMapAdapter.html',1,'DGtal']]],
  ['straightlinefrom2points_6747',['StraightLineFrom2Points',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1StraightLineFrom2Points.html',1,'DGtal']]],
  ['stricttruncationfunctor_6748',['StrictTruncationFunctor',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1StrictTruncationFunctor.html',1,'DGtal::functors']]],
  ['style2dfactory_6749',['Style2DFactory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1Style2DFactory.html',1,'DGtal']]],
  ['subcospace_6750',['Subcospace',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SpaceND_1_1Subcospace.html',1,'DGtal::SpaceND']]],
  ['subspace_6751',['Subspace',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1SpaceND_1_1Subspace.html',1,'DGtal::SpaceND']]],
  ['surfaces_6752',['Surfaces',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Surfaces.html',1,'DGtal']]],
  ['surfeladjacency_6753',['SurfelAdjacency',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelAdjacency.html',1,'DGtal']]],
  ['surfeladjacency_3c_20kspace_3a_3adimension_20_3e_6754',['SurfelAdjacency&lt; KSpace::dimension &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelAdjacency.html',1,'']]],
  ['surfelmap_6755',['SurfelMap',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1DigitalSurface_1_1SurfelMap.html',1,'DGtal::DigitalSurface&lt; TDigitalSurfaceContainer &gt;::SurfelMap&lt; Value &gt;'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1KhalimskyPreSpaceND_1_1SurfelMap.html',1,'DGtal::KhalimskyPreSpaceND&lt; dim, TInteger &gt;::SurfelMap&lt; class &gt;'],['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1KhalimskySpaceND_1_1SurfelMap.html',1,'DGtal::KhalimskySpaceND&lt; dim, TInteger &gt;::SurfelMap&lt; class &gt;']]],
  ['surfelneighborhood_6756',['SurfelNeighborhood',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelNeighborhood.html',1,'DGtal']]],
  ['surfelneighborhood_3c_20kspace_20_3e_6757',['SurfelNeighborhood&lt; KSpace &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1SurfelNeighborhood.html',1,'']]],
  ['surfelsetpredicate_6758',['SurfelSetPredicate',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1SurfelSetPredicate.html',1,'DGtal::functors']]],
  ['surfelsetpredicate_3c_20surfelset_2c_20surfel_20_3e_6759',['SurfelSetPredicate&lt; SurfelSet, Surfel &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1SurfelSetPredicate.html',1,'']]],
  ['swappableiteratorconcept_6760',['SwappableIteratorConcept',['https://dgtal-team.github.io/doc-nightly/structboost__concepts_1_1SwappableIteratorConcept.html',1,'boost_concepts']]]
];
