var searchData=
[
  ['pair1st_6554',['Pair1st',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1Pair1st.html',1,'DGtal::functors']]],
  ['pair1st_3c_20point_20_3e_6555',['Pair1st&lt; Point &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1Pair1st.html',1,'']]],
  ['pair1stmutator_6556',['Pair1stMutator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1Pair1stMutator.html',1,'DGtal::functors']]],
  ['pair2nd_6557',['Pair2nd',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1Pair2nd.html',1,'DGtal::functors']]],
  ['pair2ndmutator_6558',['Pair2ndMutator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1Pair2ndMutator.html',1,'DGtal::functors']]],
  ['pairassociativecategory_6559',['PairAssociativeCategory',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1PairAssociativeCategory.html',1,'DGtal']]],
  ['pairassociativecontainer_6560',['PairAssociativeContainer',['https://dgtal-team.github.io/doc-nightly/structboost_1_1PairAssociativeContainer.html',1,'boost']]],
  ['parallelstrip_6561',['ParallelStrip',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1ParallelStrip.html',1,'DGtal']]],
  ['parametricshapearclengthfunctor_6562',['ParametricShapeArcLengthFunctor',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1ParametricShapeArcLengthFunctor.html',1,'DGtal']]],
  ['parametricshapecurvaturefunctor_6563',['ParametricShapeCurvatureFunctor',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1ParametricShapeCurvatureFunctor.html',1,'DGtal']]],
  ['parametricshapetangentfunctor_6564',['ParametricShapeTangentFunctor',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1ParametricShapeTangentFunctor.html',1,'DGtal']]],
  ['patatepoint_6565',['PatatePoint',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1SphereFittingEstimator_1_1PatatePoint.html',1,'DGtal::functors::SphereFittingEstimator']]],
  ['path_6566',['Path',['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1Path.html',1,'LibBoard']]],
  ['pattern_6567',['Pattern',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Pattern.html',1,'DGtal']]],
  ['pattern_3c_20fraction_20_3e_6568',['Pattern&lt; Fraction &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Pattern.html',1,'']]],
  ['pgmreader_6569',['PGMReader',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1PGMReader.html',1,'DGtal']]],
  ['pgmwriter_6570',['PGMWriter',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1PGMWriter.html',1,'DGtal']]],
  ['planeshape_6571',['PlaneShape',['../structPlaneShape.html',1,'']]],
  ['point_6572',['Point',['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1Point.html',1,'LibBoard']]],
  ['point2dembedderin3d_6573',['Point2DEmbedderIn3D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1Point2DEmbedderIn3D.html',1,'DGtal::functors']]],
  ['point2shapepredicate_6574',['Point2ShapePredicate',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1Point2ShapePredicate.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_6575',['Point2ShapePredicateComparator',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1Point2ShapePredicateComparator.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_3c_20t_2c_20false_2c_20false_20_3e_6576',['Point2ShapePredicateComparator&lt; T, false, false &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1Point2ShapePredicateComparator_3_01T_00_01false_00_01false_01_4.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_3c_20t_2c_20false_2c_20true_20_3e_6577',['Point2ShapePredicateComparator&lt; T, false, true &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1Point2ShapePredicateComparator_3_01T_00_01false_00_01true_01_4.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_3c_20t_2c_20true_2c_20false_20_3e_6578',['Point2ShapePredicateComparator&lt; T, true, false &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1Point2ShapePredicateComparator_3_01T_00_01true_00_01false_01_4.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_3c_20t_2c_20true_2c_20true_20_3e_6579',['Point2ShapePredicateComparator&lt; T, true, true &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1Point2ShapePredicateComparator_3_01T_00_01true_00_01true_01_4.html',1,'DGtal::functors']]],
  ['pointfunctorfrompointpredicateanddomain_6580',['PointFunctorFromPointPredicateAndDomain',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1PointFunctorFromPointPredicateAndDomain.html',1,'DGtal::functors']]],
  ['pointfunctorpredicate_6581',['PointFunctorPredicate',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1PointFunctorPredicate.html',1,'DGtal::functors']]],
  ['pointlistreader_6582',['PointListReader',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1PointListReader.html',1,'DGtal']]],
  ['pointvaluecompare_6583',['PointValueCompare',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1detail_1_1PointValueCompare.html',1,'DGtal::detail']]],
  ['pointvector_6584',['PointVector',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_202_2c_20double_20_3e_6585',['PointVector&lt; 2, double &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PointVector.html',1,'']]],
  ['pointvector_3c_202_2c_20integer_20_3e_6586',['PointVector&lt; 2, Integer &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PointVector.html',1,'']]],
  ['pointvector_3c_203_2c_20double_20_3e_6587',['PointVector&lt; 3, double &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PointVector.html',1,'']]],
  ['pointvector_3c_203_2c_20internalinteger_20_3e_6588',['PointVector&lt; 3, InternalInteger &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PointVector.html',1,'']]],
  ['pointvector_3c_203_2c_20internalscalar_20_3e_6589',['PointVector&lt; 3, InternalScalar &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PointVector.html',1,'']]],
  ['pointvector_3c_20dim_2c_20integer_20_3e_6590',['PointVector&lt; dim, Integer &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PointVector.html',1,'']]],
  ['pointvector_3c_20space_3a_3adimension_2c_20real_20_3e_6591',['PointVector&lt; Space::dimension, Real &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PointVector.html',1,'']]],
  ['polarpointcomparatorby2x2detcomputer_6592',['PolarPointComparatorBy2x2DetComputer',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1functors_1_1PolarPointComparatorBy2x2DetComputer.html',1,'DGtal::functors']]],
  ['polygond3d_6593',['PolygonD3D',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1Display3D_1_1PolygonD3D.html',1,'DGtal::Display3D']]],
  ['polyline_6594',['Polyline',['https://dgtal-team.github.io/doc-nightly/structLibBoard_1_1Polyline.html',1,'LibBoard']]],
  ['posdepscaledepscestimator_6595',['PosDepScaleDepSCEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1detail_1_1PosDepScaleDepSCEstimator.html',1,'DGtal::detail']]],
  ['posdepscaledepscestimator_3c_20dcacomputer_2c_20detail_3a_3adistancefromdca_20_3e_6596',['PosDepScaleDepSCEstimator&lt; DCAComputer, detail::DistanceFromDCA &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1detail_1_1PosDepScaleDepSCEstimator.html',1,'']]],
  ['posdepscaleindepscestimator_6597',['PosDepScaleIndepSCEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1detail_1_1PosDepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posdepscaleindepscestimator_3c_20dcacomputer_2c_20detail_3a_3anormalvectorfromdca_20_3e_6598',['PosDepScaleIndepSCEstimator&lt; DCAComputer, detail::NormalVectorFromDCA &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1detail_1_1PosDepScaleIndepSCEstimator.html',1,'']]],
  ['posdepscaleindepscestimator_3c_20dcacomputer_2c_20detail_3a_3atangentvectorfromdca_20_3e_6599',['PosDepScaleIndepSCEstimator&lt; DCAComputer, detail::TangentVectorFromDCA &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1detail_1_1PosDepScaleIndepSCEstimator.html',1,'']]],
  ['posindepscaledepscestimator_6600',['PosIndepScaleDepSCEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1detail_1_1PosIndepScaleDepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaledepscestimator_3c_20dcacomputer_2c_20detail_3a_3acurvaturefromdca_3c_20isccw_20_3e_20_3e_6601',['PosIndepScaleDepSCEstimator&lt; DCAComputer, detail::CurvatureFromDCA&lt; isCCW &gt; &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1detail_1_1PosIndepScaleDepSCEstimator.html',1,'']]],
  ['posindepscaleindepscestimator_6602',['PosIndepScaleIndepSCEstimator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1detail_1_1PosIndepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaleindepscestimator_3c_20dsscomputer_2c_20detail_3a_3anormalizedtangentvectorfromdss_20_3e_6603',['PosIndepScaleIndepSCEstimator&lt; DSSComputer, detail::NormalizedTangentVectorFromDSS &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1detail_1_1PosIndepScaleIndepSCEstimator.html',1,'']]],
  ['posindepscaleindepscestimator_3c_20dsscomputer_2c_20detail_3a_3atangentanglefromdss_20_3e_6604',['PosIndepScaleIndepSCEstimator&lt; DSSComputer, detail::TangentAngleFromDSS &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1detail_1_1PosIndepScaleIndepSCEstimator.html',1,'']]],
  ['posindepscaleindepscestimator_3c_20dsscomputer_2c_20detail_3a_3atangentvectorfromdss_3c_20dsscomputer_20_3e_20_3e_6605',['PosIndepScaleIndepSCEstimator&lt; DSSComputer, detail::TangentVectorFromDSS&lt; DSSComputer &gt; &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1detail_1_1PosIndepScaleIndepSCEstimator.html',1,'']]],
  ['positionfunctorfrom2dpoint_6606',['PositionFunctorFrom2DPoint',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1PositionFunctorFrom2DPoint.html',1,'DGtal::functors']]],
  ['pow_6607',['POW',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1POW.html',1,'DGtal']]],
  ['pow_3c_20x_2c_200_20_3e_6608',['POW&lt; X, 0 &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1POW_3_01X_00_010_01_4.html',1,'DGtal']]],
  ['pow_3c_20x_2c_201_20_3e_6609',['POW&lt; X, 1 &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1POW_3_01X_00_011_01_4.html',1,'DGtal']]],
  ['power_5fnode_6610',['power_node',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1detail_1_1power__node.html',1,'DGtal::detail']]],
  ['powermap_6611',['PowerMap',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PowerMap.html',1,'DGtal']]],
  ['powermap_3c_20tweightimage_2c_20tpseparablemetric_2c_20timagecontainer_20_3e_6612',['PowerMap&lt; TWeightImage, TPSeparableMetric, TImageContainer &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PowerMap.html',1,'']]],
  ['ppmreader_6613',['PPMReader',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1PPMReader.html',1,'DGtal']]],
  ['ppmwriter_6614',['PPMWriter',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1PPMWriter.html',1,'DGtal']]],
  ['precelldirectioniterator_6615',['PreCellDirectionIterator',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PreCellDirectionIterator.html',1,'DGtal']]],
  ['predicatecombiner_6616',['PredicateCombiner',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1PredicateCombiner.html',1,'DGtal::functors']]],
  ['predicatecombiner_3c_20tlow_2c_20tup_2c_20andboolfct2_20_3e_6617',['PredicateCombiner&lt; Tlow, Tup, AndBoolFct2 &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1PredicateCombiner.html',1,'']]],
  ['predicatefromorientationfunctor2_6618',['PredicateFromOrientationFunctor2',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PredicateFromOrientationFunctor2.html',1,'DGtal']]],
  ['predicatefromorientationfunctor2_3c_20functor_2c_20false_2c_20false_20_3e_6619',['PredicateFromOrientationFunctor2&lt; Functor, false, false &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PredicateFromOrientationFunctor2.html',1,'']]],
  ['predicatefromorientationfunctor2_3c_20functor_2c_20true_2c_20false_20_3e_6620',['PredicateFromOrientationFunctor2&lt; Functor, true, false &gt;',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1PredicateFromOrientationFunctor2.html',1,'']]],
  ['preimage2d_6621',['Preimage2D',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Preimage2D.html',1,'DGtal']]],
  ['profile_6622',['Profile',['https://dgtal-team.github.io/doc-nightly/classDGtal_1_1Profile.html',1,'DGtal']]],
  ['projector_6623',['Projector',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1Projector.html',1,'DGtal::functors']]],
  ['projector_3c_20spacend_3c_202_2c_20coordinate_20_3e_20_3e_6624',['Projector&lt; SpaceND&lt; 2, Coordinate &gt; &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1functors_1_1Projector.html',1,'']]],
  ['promote_5ftrait_6625',['promote_trait',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1promote__trait.html',1,'DGtal']]],
  ['promote_5ftrait_3c_20int32_5ft_2c_20int64_5ft_20_3e_6626',['promote_trait&lt; int32_t, int64_t &gt;',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1promote__trait_3_01int32__t_00_01int64__t_01_4.html',1,'DGtal']]],
  ['property_6627',['Property',['https://dgtal-team.github.io/doc-nightly/structDGtal_1_1DiscreteExteriorCalculus_1_1Property.html',1,'DGtal::DiscreteExteriorCalculus']]]
];
