var searchData=
[
  ['tangentbc_0',['tangentBC',['../group__estimatortools.html',1,'']]],
  ['test_20in_20dgtal_20using_20catch_1',['Unit test in DGtal using Catch',['https://dgtal-team.github.io/doc-nightly/moduleCatch.html',1,'']]],
  ['than_2050_20lines_2',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageGridVolume3dVolViewer.html',1,'']]],
  ['the_20digital_20plane_20zxz_20convex_20polygons_20with_20vertices_20at_20integer_20coordinates_3',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['https://dgtal-team.github.io/doc-nightly/moduleLatticePolytope2D.html',1,'']]],
  ['the_20fast_20marching_20method_4',['Tutorial: Local morphological opening of a 3d volume by the Fast Marching Method',['https://dgtal-team.github.io/doc-nightly/tutoFMMErosion.html',1,'']]],
  ['the_20plane_5',['Convex hull and alpha-shape in the plane',['https://dgtal-team.github.io/doc-nightly/moduleHull2D.html',1,'']]],
  ['thick_20segment_20recognition_6',['Alpha-thick Segment Recognition',['https://dgtal-team.github.io/doc-nightly/moduleAlphaThickSegmentReco.html',1,'']]],
  ['to_20use_20dgtal_20in_20my_20own_20project_7',['How to use DGtal in my own project ?',['https://dgtal-team.github.io/doc-nightly/moduleHowToUseDGtal.html',1,'']]],
  ['to_20use_20dgtal_20in_20my_20own_20project_20with_20other_20build_20systems_8',['How to use DGtal in my own project with other build systems?',['https://dgtal-team.github.io/doc-nightly/moduleHowToUseDGtal-qmake.html',1,'']]],
  ['tools_9',['Estimator Tools',['../estimators_Doc.html',1,'']]],
  ['tools_20and_20algorithms_20library_10',['DGtalTools - Digital Geometry Tools and Algorithms Library.',['../index.html',1,'']]],
  ['topology_20and_20digital_20objects_11',['Digital topology and digital objects',['https://dgtal-team.github.io/doc-nightly/moduleDigitalTopology.html',1,'']]],
  ['topology_20concepts_20and_20models_20part_20i_20models_20of_20graph_12',['Topology Concepts and Models (part I, models of graph)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts1.html',1,'']]],
  ['topology_20concepts_20and_20models_20part_20ii_20digital_20surfaces_20surfel_20predicates_13',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts2.html',1,'']]],
  ['topology_20package_14',['Topology package',['https://dgtal-team.github.io/doc-nightly/packageTopology.html',1,'']]],
  ['topology_20unoriented_20and_20oriented_20cells_20incidence_15',['Cellular grid space and topology, unoriented and oriented cells, incidence',['https://dgtal-team.github.io/doc-nightly/moduleCellularTopology.html',1,'']]],
  ['tortorelli_20functional_16',['Image restoration and inpainting with Ambrosio-Tortorelli functional',['../group__imageprocessingtools.html',1,'']]],
  ['transformation_17',['Tutorial &quot;Image -&gt; Region -&gt; Distance Transformation&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageRegionDT.html',1,'']]],
  ['transformations_18',['Geometric transformations',['https://dgtal-team.github.io/doc-nightly/moduleGeometricTransform.html',1,'']]],
  ['tutorial_20file_20grid_20curve_20ranges_19',['Tutorial &quot;File -&gt; Grid Curve -&gt; Ranges&quot;',['https://dgtal-team.github.io/doc-nightly/tutoFileGridCurveRanges.html',1,'']]],
  ['tutorial_20generated_20shape_20grid_20curve_20length_20estimation_20',['Tutorial &quot;Generated shape -&gt; Grid curve -&gt; Length estimation&quot;',['https://dgtal-team.github.io/doc-nightly/tutoShapeGridCurveEstimator.html',1,'']]],
  ['tutorial_20image_20imageadapter_3a_20some_20simple_20image_20manipulations_21',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageManipulations.html',1,'']]],
  ['tutorial_20image_20region_20distance_20transformation_22',['Tutorial &quot;Image -&gt; Region -&gt; Distance Transformation&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageRegionDT.html',1,'']]],
  ['tutorial_20image_20region_20grid_20curve_20extracting_20level_20set_20boundary_20from_20image_23',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt;  Extracting level set boundary from Image&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageGridCurveExtraction.html',1,'']]],
  ['tutorial_20image_20region_20grid_20curve_20length_20estimation_24',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt; Length estimation&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageGridCurveEstimator.html',1,'']]],
  ['tutorial_20image_20region_20volume_203dvolviewer_20_3a_20a_20simple_203d_20volume_20viewer_20in_20less_20than_2050_20lines_25',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageGridVolume3dVolViewer.html',1,'']]],
  ['tutorial_3a_20local_20morphological_20opening_20of_20a_203d_20volume_20by_20the_20fast_20marching_20method_26',['Tutorial: Local morphological opening of a 3d volume by the Fast Marching Method',['https://dgtal-team.github.io/doc-nightly/tutoFMMErosion.html',1,'']]],
  ['tutorial_3a_20making_20a_20polyhedron_20from_20a_20digital_20object_27',['Tutorial: making a polyhedron from a digital object',['https://dgtal-team.github.io/doc-nightly/tutoPolyhedralisation.html',1,'']]],
  ['tutorial_3a_20surface_20area_20estimation_28',['Tutorial: Surface area estimation',['https://dgtal-team.github.io/doc-nightly/tutoAreaSurface.html',1,'']]],
  ['tutorial_3a_20volumetric_20analysis_20and_20granulometry_29',['Tutorial: Volumetric analysis and Granulometry',['https://dgtal-team.github.io/doc-nightly/tutoVolDTGranulometry.html',1,'']]],
  ['tutorials_30',['Tutorials',['https://dgtal-team.github.io/doc-nightly/packageTutorials.html',1,'']]]
];
