var searchData=
[
  ['i_20models_20of_20graph_0',['Topology Concepts and Models (part I, models of graph)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts1.html',1,'']]],
  ['ii_20digital_20surfaces_20surfel_20predicates_1',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts2.html',1,'']]],
  ['image_20and_20digital_20object_20import_20export_2',['Image and digital object import/export',['https://dgtal-team.github.io/doc-nightly/moduleIO.html',1,'']]],
  ['image_20concepts_3',['Main Image Concepts',['https://dgtal-team.github.io/doc-nightly/packageImageConcepts.html',1,'']]],
  ['image_20imageadapter_3a_20some_20simple_20image_20manipulations_4',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageManipulations.html',1,'']]],
  ['image_20package_5',['Image package',['https://dgtal-team.github.io/doc-nightly/packageImage.html',1,'']]],
  ['image_20processing_6',['Image processing',['../imageProcessing.html',1,'']]],
  ['image_20region_20distance_20transformation_7',['Tutorial &quot;Image -&gt; Region -&gt; Distance Transformation&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageRegionDT.html',1,'']]],
  ['image_20region_20grid_20curve_20extracting_20level_20set_20boundary_20from_20image_8',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt;  Extracting level set boundary from Image&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageGridCurveExtraction.html',1,'']]],
  ['image_20region_20grid_20curve_20length_20estimation_9',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt; Length estimation&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageGridCurveEstimator.html',1,'']]],
  ['image_20region_20volume_203dvolviewer_20_3a_20a_20simple_203d_20volume_20viewer_20in_20less_20than_2050_20lines_10',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageGridVolume3dVolViewer.html',1,'']]],
  ['image_20restoration_20and_20inpainting_20with_20ambrosio_20tortorelli_20functional_11',['Image restoration and inpainting with Ambrosio-Tortorelli functional',['../moduleAT.html',1,'']]],
  ['imageadapter_3a_20some_20simple_20image_20manipulations_12',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageManipulations.html',1,'']]],
  ['imageprocessing_20at_20u0_20v1_13',['imageProcessing/at-u0-v1',['../DocATu0v1.html',1,'']]],
  ['imageprocessing_20at_20u2_20v0_14',['imageProcessing/at-u2-v0',['../DocATu2v0.html',1,'']]],
  ['imageprocessing_20atv_20u2_20v0_15',['imageProcessing/atv-u2-v0',['../DocATVu2v0.html',1,'']]],
  ['images_16',['Images',['https://dgtal-team.github.io/doc-nightly/moduleImages.html',1,'']]],
  ['images_20in_20dgtal_17',['Handle large images in DGtal',['https://dgtal-team.github.io/doc-nightly/moduleBigImages.html',1,'']]],
  ['img2freeman_18',['img2freeman',['../img2freeman.html',1,'']]],
  ['imgaddnoise_19',['imgAddNoise',['../imgAddNoise.html',1,'']]],
  ['implementation_20of_20geometric_20predicates_20',['Implementation of geometric predicates',['https://dgtal-team.github.io/doc-nightly/moduleGeometricPredicates.html',1,'']]],
  ['import_20export_21',['Image and digital object import/export',['https://dgtal-team.github.io/doc-nightly/moduleIO.html',1,'']]],
  ['in_20dgtal_22',['in dgtal',['https://dgtal-team.github.io/doc-nightly/moduleFAQGit.html',1,'Git/Github source code management in DGtal'],['https://dgtal-team.github.io/doc-nightly/moduleBigImages.html',1,'Handle large images in DGtal']]],
  ['in_20dgtal_20using_20catch_23',['Unit test in DGtal using Catch',['https://dgtal-team.github.io/doc-nightly/moduleCatch.html',1,'']]],
  ['in_20digital_20spaces_24',['Sets of points in digital spaces',['https://dgtal-team.github.io/doc-nightly/moduleDigitalSets.html',1,'']]],
  ['in_20less_20than_2050_20lines_25',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageGridVolume3dVolViewer.html',1,'']]],
  ['in_20my_20own_20project_26',['How to use DGtal in my own project ?',['https://dgtal-team.github.io/doc-nightly/moduleHowToUseDGtal.html',1,'']]],
  ['in_20my_20own_20project_20with_20other_20build_20systems_27',['How to use DGtal in my own project with other build systems?',['https://dgtal-team.github.io/doc-nightly/moduleHowToUseDGtal-qmake.html',1,'']]],
  ['in_20the_20digital_20plane_20zxz_20convex_20polygons_20with_20vertices_20at_20integer_20coordinates_28',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['https://dgtal-team.github.io/doc-nightly/moduleLatticePolytope2D.html',1,'']]],
  ['in_20the_20plane_29',['Convex hull and alpha-shape in the plane',['https://dgtal-team.github.io/doc-nightly/moduleHull2D.html',1,'']]],
  ['incidence_30',['Cellular grid space and topology, unoriented and oriented cells, incidence',['https://dgtal-team.github.io/doc-nightly/moduleCellularTopology.html',1,'']]],
  ['inpainting_20with_20ambrosio_20tortorelli_20functional_31',['Image restoration and inpainting with Ambrosio-Tortorelli functional',['../moduleAT.html',1,'']]],
  ['integer_20computations_32',['Integer computations',['https://dgtal-team.github.io/doc-nightly/moduleIntegerComputations.html',1,'']]],
  ['integer_20concepts_33',['Number and Integer Concepts',['https://dgtal-team.github.io/doc-nightly/moduleNumber.html',1,'']]],
  ['integer_20coordinates_34',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['https://dgtal-team.github.io/doc-nightly/moduleLatticePolytope2D.html',1,'']]],
  ['integral_20invariant_20curvature_20estimator_202d_203d_35',['Integral invariant curvature estimator 2D/3D',['https://dgtal-team.github.io/doc-nightly/moduleIntegralInvariant.html',1,'']]],
  ['interaction_20when_20using_20selection_20with_20qglviewer_20viewer3d_20stream_20mechanism_36',['Limited interaction when using selection with QGLViewer Viewer3D stream mechanism',['https://dgtal-team.github.io/doc-nightly/moduleQGLInteraction.html',1,'']]],
  ['interfacing_20with_20boost_3a_3agraph_20library_37',['Interfacing with boost::graph library',['https://dgtal-team.github.io/doc-nightly/moduleBoostGraphWrapping.html',1,'']]],
  ['into_20m_20dimensional_20space_38',['Embedding n-dimensional DEC structures into m-dimensional space',['https://dgtal-team.github.io/doc-nightly/moduleDECEmbedding.html',1,'']]],
  ['introduction_39',['Introduction',['https://dgtal-team.github.io/doc-nightly/moduleIntroduction.html',1,'']]],
  ['invariant_20curvature_20estimator_202d_203d_40',['Integral invariant curvature estimator 2D/3D',['https://dgtal-team.github.io/doc-nightly/moduleIntegralInvariant.html',1,'']]],
  ['io_20package_41',['IO package',['https://dgtal-team.github.io/doc-nightly/packageIO.html',1,'']]],
  ['irreducible_20fraction_20continued_20fractions_42',['Irreducible fraction, continued fractions',['https://dgtal-team.github.io/doc-nightly/moduleIrreducibleFraction.html',1,'']]],
  ['iterators_20and_20ranges_43',['Iterators and ranges',['https://dgtal-team.github.io/doc-nightly/moduleIteratorsRanges.html',1,'']]],
  ['itk2vol_44',['itk2vol',['../itk2vol.html',1,'']]]
];
