var searchData=
[
  ['calculus_0',['Discrete exterior calculus',['https://dgtal-team.github.io/doc-nightly/moduleDECIntroduction.html',1,'']]],
  ['catch_1',['Unit test in DGtal using Catch',['https://dgtal-team.github.io/doc-nightly/moduleCatch.html',1,'']]],
  ['cells_20incidence_2',['Cellular grid space and topology, unoriented and oriented cells, incidence',['https://dgtal-team.github.io/doc-nightly/moduleCellularTopology.html',1,'']]],
  ['cellular_20grid_20space_20and_20topology_20unoriented_20and_20oriented_20cells_20incidence_3',['Cellular grid space and topology, unoriented and oriented cells, incidence',['https://dgtal-team.github.io/doc-nightly/moduleCellularTopology.html',1,'']]],
  ['cloning_20and_20referencing_4',['Parameter passing, cloning and referencing',['https://dgtal-team.github.io/doc-nightly/moduleCloneAndReference.html',1,'']]],
  ['coba_20plane_20recognition_20algorithm_5',['Detailed explanation of COBA plane recognition algorithm',['https://dgtal-team.github.io/doc-nightly/moduleCOBANaivePlaneRecognition.html',1,'']]],
  ['code_20management_20in_20dgtal_6',['Git/Github source code management in DGtal',['https://dgtal-team.github.io/doc-nightly/moduleFAQGit.html',1,'']]],
  ['complex_7',['Cubical Complex',['https://dgtal-team.github.io/doc-nightly/moduleCubicalComplex.html',1,'']]],
  ['computation_8',['Plane recognition and plane width computation',['https://dgtal-team.github.io/doc-nightly/modulePlaneRecognition.html',1,'']]],
  ['computations_9',['Integer computations',['https://dgtal-team.github.io/doc-nightly/moduleIntegerComputations.html',1,'']]],
  ['concepts_10',['concepts',['https://dgtal-team.github.io/doc-nightly/packageBaseConcepts.html',1,'Base Concepts'],['https://dgtal-team.github.io/doc-nightly/moduleGraphDefinitions.html',1,'Basic graph definitions and concepts'],['https://dgtal-team.github.io/doc-nightly/packageDECConcepts.html',1,'DEC Main Concepts'],['https://dgtal-team.github.io/doc-nightly/packageGeometryConcepts.html',1,'Geometry Concepts'],['https://dgtal-team.github.io/doc-nightly/packageGraphConcepts.html',1,'Graph Main Concepts'],['https://dgtal-team.github.io/doc-nightly/packageKernelConcepts.html',1,'Kernel Concepts'],['https://dgtal-team.github.io/doc-nightly/packageImageConcepts.html',1,'Main Image Concepts'],['https://dgtal-team.github.io/doc-nightly/packageMathConcepts.html',1,'Math Main Concepts'],['https://dgtal-team.github.io/doc-nightly/moduleMetrics.html',1,'Metric Spaces, Digital Metric Spaces and Related Concepts'],['https://dgtal-team.github.io/doc-nightly/moduleNumber.html',1,'Number and Integer Concepts'],['https://dgtal-team.github.io/doc-nightly/packageShapesConcepts.html',1,'Shape Concepts']]],
  ['concepts_20and_20models_11',['Arithmetic Concepts and Models',['https://dgtal-team.github.io/doc-nightly/packageArithmeticConcepts.html',1,'']]],
  ['concepts_20and_20models_20part_20i_20models_20of_20graph_12',['Topology Concepts and Models (part I, models of graph)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts1.html',1,'']]],
  ['concepts_20and_20models_20part_20ii_20digital_20surfaces_20surfel_20predicates_13',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts2.html',1,'']]],
  ['containers_14',['Set operations on arbitrary containers',['https://dgtal-team.github.io/doc-nightly/moduleSetFunctions.html',1,'']]],
  ['continued_20fractions_15',['Irreducible fraction, continued fractions',['https://dgtal-team.github.io/doc-nightly/moduleIrreducibleFraction.html',1,'']]],
  ['contourgenerator_16',['contourGenerator',['../contourGenerator.html',1,'']]],
  ['converters_17',['Converters',['../converters.html',1,'']]],
  ['convertvol_18',['convertVol',['../convertVol.html',1,'']]],
  ['convex_20hull_20and_20alpha_20shape_20in_20the_20plane_19',['Convex hull and alpha-shape in the plane',['https://dgtal-team.github.io/doc-nightly/moduleHull2D.html',1,'']]],
  ['convex_20polygons_20with_20vertices_20at_20integer_20coordinates_20',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['https://dgtal-team.github.io/doc-nightly/moduleLatticePolytope2D.html',1,'']]],
  ['coordinates_21',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['https://dgtal-team.github.io/doc-nightly/moduleLatticePolytope2D.html',1,'']]],
  ['covariance_20measure_20and_20geometry_20estimation_22',['Digital Voronoi Covariance Measure and geometry estimation',['https://dgtal-team.github.io/doc-nightly/moduleVCM.html',1,'']]],
  ['criticalkernelsthinning3d_23',['criticalKernelsThinning3D',['../criticalKernelsThinning3D.html',1,'']]],
  ['cubical_20complex_24',['Cubical Complex',['https://dgtal-team.github.io/doc-nightly/moduleCubicalComplex.html',1,'']]],
  ['curvature_20estimator_202d_203d_25',['Integral invariant curvature estimator 2D/3D',['https://dgtal-team.github.io/doc-nightly/moduleIntegralInvariant.html',1,'']]],
  ['curvaturebc_26',['curvatureBC',['../curvatureBC.html',1,'']]],
  ['curvaturemcms_27',['curvatureMCMS',['../curvatureMCMS.html',1,'']]],
  ['curvaturescalespacebcc_28',['curvatureScaleSpaceBCC',['../curvatureScaleSpaceBCC.html',1,'']]],
  ['curve_20extracting_20level_20set_20boundary_20from_20image_29',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt;  Extracting level set boundary from Image&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageGridCurveExtraction.html',1,'']]],
  ['curve_20length_20estimation_30',['curve length estimation',['https://dgtal-team.github.io/doc-nightly/tutoShapeGridCurveEstimator.html',1,'Tutorial &quot;Generated shape -&gt; Grid curve -&gt; Length estimation&quot;'],['https://dgtal-team.github.io/doc-nightly/tutoImageGridCurveEstimator.html',1,'Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt; Length estimation&quot;']]],
  ['curve_20ranges_31',['Tutorial &quot;File -&gt; Grid Curve -&gt; Ranges&quot;',['https://dgtal-team.github.io/doc-nightly/tutoFileGridCurveRanges.html',1,'']]]
];
