var searchData=
[
  ['a_203d_20volume_20by_20the_20fast_20marching_20method_0',['Tutorial: Local morphological opening of a 3d volume by the Fast Marching Method',['https://dgtal-team.github.io/doc-nightly/tutoFMMErosion.html',1,'']]],
  ['a_20polyhedron_20from_20a_20digital_20object_1',['Tutorial: making a polyhedron from a digital object',['https://dgtal-team.github.io/doc-nightly/tutoPolyhedralisation.html',1,'']]],
  ['a_20simple_203d_20volume_20viewer_20in_20less_20than_2050_20lines_2',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageGridVolume3dVolViewer.html',1,'']]],
  ['a_20stream_20mechanism_20for_20displaying_202d_20digital_20objects_3',['Board2D: a stream mechanism for displaying 2D digital objects',['https://dgtal-team.github.io/doc-nightly/moduleBoard2D.html',1,'']]],
  ['a_20stream_20mechanism_20for_20displaying_203d_20dgtal_20objects_4',['Display3D: a stream mechanism for displaying 3D DGtal objects',['https://dgtal-team.github.io/doc-nightly/moduleDisplay3D.html',1,'']]],
  ['algorithm_5',['Detailed explanation of COBA plane recognition algorithm',['https://dgtal-team.github.io/doc-nightly/moduleCOBANaivePlaneRecognition.html',1,'']]],
  ['algorithms_20library_6',['DGtalTools - Digital Geometry Tools and Algorithms Library.',['../index.html',1,'']]],
  ['alpha_20shape_20in_20the_20plane_7',['Convex hull and alpha-shape in the plane',['https://dgtal-team.github.io/doc-nightly/moduleHull2D.html',1,'']]],
  ['alpha_20thick_20segment_20recognition_8',['Alpha-thick Segment Recognition',['https://dgtal-team.github.io/doc-nightly/moduleAlphaThickSegmentReco.html',1,'']]],
  ['ambrosio_20tortorelli_20functional_9',['Image restoration and inpainting with Ambrosio-Tortorelli functional',['../moduleAT.html',1,'']]],
  ['analysis_20and_20granulometry_10',['Tutorial: Volumetric analysis and Granulometry',['https://dgtal-team.github.io/doc-nightly/tutoVolDTGranulometry.html',1,'']]],
  ['analysis_20of_20one_20dimensional_20discrete_20structures_11',['Analysis of one-dimensional discrete structures',['https://dgtal-team.github.io/doc-nightly/moduleGridCurveAnalysis.html',1,'']]],
  ['analysis_20using_20separable_20processes_12',['nD Volumetric Analysis using Separable Processes',['https://dgtal-team.github.io/doc-nightly/moduleVolumetric.html',1,'']]],
  ['and_20algorithms_20library_13',['DGtalTools - Digital Geometry Tools and Algorithms Library.',['../index.html',1,'']]],
  ['and_20alpha_20shape_20in_20the_20plane_14',['Convex hull and alpha-shape in the plane',['https://dgtal-team.github.io/doc-nightly/moduleHull2D.html',1,'']]],
  ['and_20concepts_15',['Basic graph definitions and concepts',['https://dgtal-team.github.io/doc-nightly/moduleGraphDefinitions.html',1,'']]],
  ['and_20digital_20object_20import_20export_16',['Image and digital object import/export',['https://dgtal-team.github.io/doc-nightly/moduleIO.html',1,'']]],
  ['and_20digital_20objects_17',['Digital topology and digital objects',['https://dgtal-team.github.io/doc-nightly/moduleDigitalTopology.html',1,'']]],
  ['and_20digitizers_18',['Shapes, Shapers and Digitizers',['https://dgtal-team.github.io/doc-nightly/moduleShape.html',1,'']]],
  ['and_20domains_19',['Digital Spaces, Points, Vectors and Domains',['https://dgtal-team.github.io/doc-nightly/moduleSpacePointVectorDomain.html',1,'']]],
  ['and_20geometry_20estimation_20',['Digital Voronoi Covariance Measure and geometry estimation',['https://dgtal-team.github.io/doc-nightly/moduleVCM.html',1,'']]],
  ['and_20granulometry_21',['Tutorial: Volumetric analysis and Granulometry',['https://dgtal-team.github.io/doc-nightly/tutoVolDTGranulometry.html',1,'']]],
  ['and_20inpainting_20with_20ambrosio_20tortorelli_20functional_22',['Image restoration and inpainting with Ambrosio-Tortorelli functional',['../moduleAT.html',1,'']]],
  ['and_20integer_20concepts_23',['Number and Integer Concepts',['https://dgtal-team.github.io/doc-nightly/moduleNumber.html',1,'']]],
  ['and_20models_24',['Arithmetic Concepts and Models',['https://dgtal-team.github.io/doc-nightly/packageArithmeticConcepts.html',1,'']]],
  ['and_20models_20part_20i_20models_20of_20graph_25',['Topology Concepts and Models (part I, models of graph)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts1.html',1,'']]],
  ['and_20models_20part_20ii_20digital_20surfaces_20surfel_20predicates_26',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts2.html',1,'']]],
  ['and_20plane_20width_20computation_27',['Plane recognition and plane width computation',['https://dgtal-team.github.io/doc-nightly/modulePlaneRecognition.html',1,'']]],
  ['and_20ranges_28',['Iterators and ranges',['https://dgtal-team.github.io/doc-nightly/moduleIteratorsRanges.html',1,'']]],
  ['and_20referencing_29',['Parameter passing, cloning and referencing',['https://dgtal-team.github.io/doc-nightly/moduleCloneAndReference.html',1,'']]],
  ['and_20related_20concepts_30',['Metric Spaces, Digital Metric Spaces and Related Concepts',['https://dgtal-team.github.io/doc-nightly/moduleMetrics.html',1,'']]],
  ['and_20segments_31',['Digital straight lines and segments',['https://dgtal-team.github.io/doc-nightly/moduleArithDSSReco.html',1,'']]],
  ['and_20subsegments_32',['Patterns, digital straight lines and subsegments',['https://dgtal-team.github.io/doc-nightly/moduleDigitalStraightness.html',1,'']]],
  ['and_20topology_20unoriented_20and_20oriented_20cells_20incidence_33',['Cellular grid space and topology, unoriented and oriented cells, incidence',['https://dgtal-team.github.io/doc-nightly/moduleCellularTopology.html',1,'']]],
  ['arbitrary_20containers_34',['Set operations on arbitrary containers',['https://dgtal-team.github.io/doc-nightly/moduleSetFunctions.html',1,'']]],
  ['area_20estimation_35',['Tutorial: Surface area estimation',['https://dgtal-team.github.io/doc-nightly/tutoAreaSurface.html',1,'']]],
  ['arithmetic_20concepts_20and_20models_36',['Arithmetic Concepts and Models',['https://dgtal-team.github.io/doc-nightly/packageArithmeticConcepts.html',1,'']]],
  ['arithmetic_20package_37',['Arithmetic package',['https://dgtal-team.github.io/doc-nightly/packageArithmetic.html',1,'']]],
  ['at_20integer_20coordinates_38',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['https://dgtal-team.github.io/doc-nightly/moduleLatticePolytope2D.html',1,'']]],
  ['at_20u0_20v1_39',['imageProcessing/at-u0-v1',['../DocATu0v1.html',1,'']]],
  ['at_20u2_20v0_40',['imageProcessing/at-u2-v0',['../DocATu2v0.html',1,'']]],
  ['atv_20u2_20v0_41',['imageProcessing/atv-u2-v0',['../DocATVu2v0.html',1,'']]]
];
