var searchData=
[
  ['package_0',['package',['https://dgtal-team.github.io/doc-nightly/packageArithmetic.html',1,'Arithmetic package'],['https://dgtal-team.github.io/doc-nightly/packageBase.html',1,'Base package'],['https://dgtal-team.github.io/doc-nightly/packageDEC.html',1,'DEC package'],['https://dgtal-team.github.io/doc-nightly/packageGeometry.html',1,'Geometry package'],['https://dgtal-team.github.io/doc-nightly/packageGraph.html',1,'Graph package'],['https://dgtal-team.github.io/doc-nightly/packageImage.html',1,'Image package'],['https://dgtal-team.github.io/doc-nightly/packageIO.html',1,'IO package'],['https://dgtal-team.github.io/doc-nightly/packageKernel.html',1,'Kernel package'],['https://dgtal-team.github.io/doc-nightly/packageMath.html',1,'Mathematical package'],['https://dgtal-team.github.io/doc-nightly/packageShapes.html',1,'Shapes package'],['https://dgtal-team.github.io/doc-nightly/packageTopology.html',1,'Topology package']]],
  ['parameter_20passing_20cloning_20and_20referencing_1',['Parameter passing, cloning and referencing',['https://dgtal-team.github.io/doc-nightly/moduleCloneAndReference.html',1,'']]],
  ['part_20i_20models_20of_20graph_2',['Topology Concepts and Models (part I, models of graph)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts1.html',1,'']]],
  ['part_20ii_20digital_20surfaces_20surfel_20predicates_3',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts2.html',1,'']]],
  ['passing_20cloning_20and_20referencing_4',['Parameter passing, cloning and referencing',['https://dgtal-team.github.io/doc-nightly/moduleCloneAndReference.html',1,'']]],
  ['patterns_20digital_20straight_20lines_20and_20subsegments_5',['Patterns, digital straight lines and subsegments',['https://dgtal-team.github.io/doc-nightly/moduleDigitalStraightness.html',1,'']]],
  ['patterntriangulation_6',['patternTriangulation',['../group__visualizationtools.html',1,'']]],
  ['plane_7',['Convex hull and alpha-shape in the plane',['https://dgtal-team.github.io/doc-nightly/moduleHull2D.html',1,'']]],
  ['plane_20recognition_20algorithm_8',['Detailed explanation of COBA plane recognition algorithm',['https://dgtal-team.github.io/doc-nightly/moduleCOBANaivePlaneRecognition.html',1,'']]],
  ['plane_20recognition_20and_20plane_20width_20computation_9',['Plane recognition and plane width computation',['https://dgtal-team.github.io/doc-nightly/modulePlaneRecognition.html',1,'']]],
  ['plane_20zxz_20convex_20polygons_20with_20vertices_20at_20integer_20coordinates_10',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['https://dgtal-team.github.io/doc-nightly/moduleLatticePolytope2D.html',1,'']]],
  ['points_20in_20digital_20spaces_11',['Sets of points in digital spaces',['https://dgtal-team.github.io/doc-nightly/moduleDigitalSets.html',1,'']]],
  ['points_20vectors_20and_20domains_12',['Digital Spaces, Points, Vectors and Domains',['https://dgtal-team.github.io/doc-nightly/moduleSpacePointVectorDomain.html',1,'']]],
  ['poisson_20problem_13',['Poisson problem',['https://dgtal-team.github.io/doc-nightly/moduleDECPoisson.html',1,'']]],
  ['polygons_20with_20vertices_20at_20integer_20coordinates_14',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['https://dgtal-team.github.io/doc-nightly/moduleLatticePolytope2D.html',1,'']]],
  ['polyhedron_20from_20a_20digital_20object_15',['Tutorial: making a polyhedron from a digital object',['https://dgtal-team.github.io/doc-nightly/tutoPolyhedralisation.html',1,'']]],
  ['polynomials_16',['Multivariate polynomials',['https://dgtal-team.github.io/doc-nightly/modulePolynomial.html',1,'']]],
  ['polytopes_20in_20the_20digital_20plane_20zxz_20convex_20polygons_20with_20vertices_20at_20integer_20coordinates_17',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['https://dgtal-team.github.io/doc-nightly/moduleLatticePolytope2D.html',1,'']]],
  ['predicates_18',['predicates',['https://dgtal-team.github.io/doc-nightly/moduleGeometricPredicates.html',1,'Implementation of geometric predicates'],['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts2.html',1,'Topology Concepts and Models (part II, digital surfaces, surfel predicates)']]],
  ['preliminaries_19',['Preliminaries',['https://dgtal-team.github.io/doc-nightly/packageIntroduction.html',1,'']]],
  ['problem_20',['Poisson problem',['https://dgtal-team.github.io/doc-nightly/moduleDECPoisson.html',1,'']]],
  ['processes_21',['nD Volumetric Analysis using Separable Processes',['https://dgtal-team.github.io/doc-nightly/moduleVolumetric.html',1,'']]],
  ['processing_22',['Image processing',['../imageProcessing.html',1,'']]],
  ['project_23',['How to use DGtal in my own project ?',['https://dgtal-team.github.io/doc-nightly/moduleHowToUseDGtal.html',1,'']]],
  ['project_20with_20other_20build_20systems_24',['How to use DGtal in my own project with other build systems?',['https://dgtal-team.github.io/doc-nightly/moduleHowToUseDGtal-qmake.html',1,'']]],
  ['propagation_25',['Propagation',['https://dgtal-team.github.io/doc-nightly/moduleDECPropagation.html',1,'']]]
];
