var searchData=
[
  ['dec_20main_20concepts_0',['DEC Main Concepts',['https://dgtal-team.github.io/doc-nightly/packageDECConcepts.html',1,'']]],
  ['dec_20package_1',['DEC package',['https://dgtal-team.github.io/doc-nightly/packageDEC.html',1,'']]],
  ['dec_20structures_20into_20m_20dimensional_20space_2',['Embedding n-dimensional DEC structures into m-dimensional space',['https://dgtal-team.github.io/doc-nightly/moduleDECEmbedding.html',1,'']]],
  ['decomposition_3',['Helmoltz decomposition',['https://dgtal-team.github.io/doc-nightly/moduleDECHelmoltz.html',1,'']]],
  ['definitions_20and_20concepts_4',['Basic graph definitions and concepts',['https://dgtal-team.github.io/doc-nightly/moduleGraphDefinitions.html',1,'']]],
  ['detailed_20explanation_20of_20coba_20plane_20recognition_20algorithm_5',['Detailed explanation of COBA plane recognition algorithm',['https://dgtal-team.github.io/doc-nightly/moduleCOBANaivePlaneRecognition.html',1,'']]],
  ['dgtal_6',['dgtal',['https://dgtal-team.github.io/doc-nightly/moduleBuildDGtal.html',1,'Building DGtal'],['https://dgtal-team.github.io/doc-nightly/moduleFAQGit.html',1,'Git/Github source code management in DGtal'],['https://dgtal-team.github.io/doc-nightly/moduleBigImages.html',1,'Handle large images in DGtal']]],
  ['dgtal_20in_20my_20own_20project_7',['How to use DGtal in my own project ?',['https://dgtal-team.github.io/doc-nightly/moduleHowToUseDGtal.html',1,'']]],
  ['dgtal_20in_20my_20own_20project_20with_20other_20build_20systems_8',['How to use DGtal in my own project with other build systems?',['https://dgtal-team.github.io/doc-nightly/moduleHowToUseDGtal-qmake.html',1,'']]],
  ['dgtal_20objects_9',['Display3D: a stream mechanism for displaying 3D DGtal objects',['https://dgtal-team.github.io/doc-nightly/moduleDisplay3D.html',1,'']]],
  ['dgtal_20using_20catch_10',['Unit test in DGtal using Catch',['https://dgtal-team.github.io/doc-nightly/moduleCatch.html',1,'']]],
  ['dgtaltools_20digital_20geometry_20tools_20and_20algorithms_20library_11',['DGtalTools - Digital Geometry Tools and Algorithms Library.',['../index.html',1,'']]],
  ['dicom2vol_12',['dicom2vol',['../group__convertertools.html',1,'']]],
  ['digital_20geometry_20tools_20and_20algorithms_20library_13',['DGtalTools - Digital Geometry Tools and Algorithms Library.',['../index.html',1,'']]],
  ['digital_20metric_20spaces_20and_20related_20concepts_14',['Metric Spaces, Digital Metric Spaces and Related Concepts',['https://dgtal-team.github.io/doc-nightly/moduleMetrics.html',1,'']]],
  ['digital_20object_15',['Tutorial: making a polyhedron from a digital object',['https://dgtal-team.github.io/doc-nightly/tutoPolyhedralisation.html',1,'']]],
  ['digital_20object_20import_20export_16',['Image and digital object import/export',['https://dgtal-team.github.io/doc-nightly/moduleIO.html',1,'']]],
  ['digital_20objects_17',['Board2D: a stream mechanism for displaying 2D digital objects',['https://dgtal-team.github.io/doc-nightly/moduleBoard2D.html',1,'']]],
  ['digital_20plane_20zxz_20convex_20polygons_20with_20vertices_20at_20integer_20coordinates_18',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['https://dgtal-team.github.io/doc-nightly/moduleLatticePolytope2D.html',1,'']]],
  ['digital_20spaces_19',['Sets of points in digital spaces',['https://dgtal-team.github.io/doc-nightly/moduleDigitalSets.html',1,'']]],
  ['digital_20spaces_20points_20vectors_20and_20domains_20',['Digital Spaces, Points, Vectors and Domains',['https://dgtal-team.github.io/doc-nightly/moduleSpacePointVectorDomain.html',1,'']]],
  ['digital_20straight_20lines_20and_20segments_21',['Digital straight lines and segments',['https://dgtal-team.github.io/doc-nightly/moduleArithDSSReco.html',1,'']]],
  ['digital_20straight_20lines_20and_20subsegments_22',['Patterns, digital straight lines and subsegments',['https://dgtal-team.github.io/doc-nightly/moduleDigitalStraightness.html',1,'']]],
  ['digital_20surface_20estimators_20from_20surfel_20functors_23',['Local digital surface estimators from surfel functors',['https://dgtal-team.github.io/doc-nightly/LocalEstimatorsFromSurfel.html',1,'']]],
  ['digital_20surfaces_24',['digital surfaces',['https://dgtal-team.github.io/doc-nightly/moduleDigitalSurfaces.html',1,'Digital surfaces'],['https://dgtal-team.github.io/doc-nightly/moduleDigitalSurfaceHelpers.html',1,'Helpers for digital surfaces']]],
  ['digital_20surfaces_20surfel_20predicates_25',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts2.html',1,'']]],
  ['digital_20topology_20and_20digital_20objects_26',['Digital topology and digital objects',['https://dgtal-team.github.io/doc-nightly/moduleDigitalTopology.html',1,'']]],
  ['digital_20voronoi_20covariance_20measure_20and_20geometry_20estimation_27',['Digital Voronoi Covariance Measure and geometry estimation',['https://dgtal-team.github.io/doc-nightly/moduleVCM.html',1,'']]],
  ['digitizers_28',['Shapes, Shapers and Digitizers',['https://dgtal-team.github.io/doc-nightly/moduleShape.html',1,'']]],
  ['dimensional_20dec_20structures_20into_20m_20dimensional_20space_29',['Embedding n-dimensional DEC structures into m-dimensional space',['https://dgtal-team.github.io/doc-nightly/moduleDECEmbedding.html',1,'']]],
  ['dimensional_20discrete_20structures_30',['Analysis of one-dimensional discrete structures',['https://dgtal-team.github.io/doc-nightly/moduleGridCurveAnalysis.html',1,'']]],
  ['discrete_20exterior_20calculus_31',['Discrete exterior calculus',['https://dgtal-team.github.io/doc-nightly/moduleDECIntroduction.html',1,'']]],
  ['discrete_20structures_32',['Analysis of one-dimensional discrete structures',['https://dgtal-team.github.io/doc-nightly/moduleGridCurveAnalysis.html',1,'']]],
  ['display3d_3a_20a_20stream_20mechanism_20for_20displaying_203d_20dgtal_20objects_33',['Display3D: a stream mechanism for displaying 3D DGtal objects',['https://dgtal-team.github.io/doc-nightly/moduleDisplay3D.html',1,'']]],
  ['displaycontours_34',['displayContours',['../group__visualizationtools.html',1,'']]],
  ['displaying_202d_20digital_20objects_35',['Board2D: a stream mechanism for displaying 2D digital objects',['https://dgtal-team.github.io/doc-nightly/moduleBoard2D.html',1,'']]],
  ['displaying_203d_20dgtal_20objects_36',['Display3D: a stream mechanism for displaying 3D DGtal objects',['https://dgtal-team.github.io/doc-nightly/moduleDisplay3D.html',1,'']]],
  ['distance_20transformation_37',['Tutorial &quot;Image -&gt; Region -&gt; Distance Transformation&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageRegionDT.html',1,'']]],
  ['domains_38',['Digital Spaces, Points, Vectors and Domains',['https://dgtal-team.github.io/doc-nightly/moduleSpacePointVectorDomain.html',1,'']]]
];
