var searchData=
[
  ['sdp2vol_0',['sdp2vol',['../sdp2vol.html',1,'']]],
  ['segment_20recognition_1',['Alpha-thick Segment Recognition',['https://dgtal-team.github.io/doc-nightly/moduleAlphaThickSegmentReco.html',1,'']]],
  ['segments_2',['Digital straight lines and segments',['https://dgtal-team.github.io/doc-nightly/moduleArithDSSReco.html',1,'']]],
  ['selection_20with_20qglviewer_20viewer3d_20stream_20mechanism_3',['Limited interaction when using selection with QGLViewer Viewer3D stream mechanism',['https://dgtal-team.github.io/doc-nightly/moduleQGLInteraction.html',1,'']]],
  ['separable_20processes_4',['nD Volumetric Analysis using Separable Processes',['https://dgtal-team.github.io/doc-nightly/moduleVolumetric.html',1,'']]],
  ['set_20boundary_20from_20image_5',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt;  Extracting level set boundary from Image&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageGridCurveExtraction.html',1,'']]],
  ['set_20operations_20on_20arbitrary_20containers_6',['Set operations on arbitrary containers',['https://dgtal-team.github.io/doc-nightly/moduleSetFunctions.html',1,'']]],
  ['sets_20of_20points_20in_20digital_20spaces_7',['Sets of points in digital spaces',['https://dgtal-team.github.io/doc-nightly/moduleDigitalSets.html',1,'']]],
  ['shape_20concepts_8',['Shape Concepts',['https://dgtal-team.github.io/doc-nightly/packageShapesConcepts.html',1,'']]],
  ['shape_20grid_20curve_20length_20estimation_9',['Tutorial &quot;Generated shape -&gt; Grid curve -&gt; Length estimation&quot;',['https://dgtal-team.github.io/doc-nightly/tutoShapeGridCurveEstimator.html',1,'']]],
  ['shape_20in_20the_20plane_10',['Convex hull and alpha-shape in the plane',['https://dgtal-team.github.io/doc-nightly/moduleHull2D.html',1,'']]],
  ['shapegenerator_11',['shapeGenerator',['../shapeGenerator.html',1,'']]],
  ['shapers_20and_20digitizers_12',['Shapes, Shapers and Digitizers',['https://dgtal-team.github.io/doc-nightly/moduleShape.html',1,'']]],
  ['shapes_20package_13',['Shapes package',['https://dgtal-team.github.io/doc-nightly/packageShapes.html',1,'']]],
  ['shapes_20shapers_20and_20digitizers_14',['Shapes, Shapers and Digitizers',['https://dgtal-team.github.io/doc-nightly/moduleShape.html',1,'']]],
  ['shortcuts_15',['Fréchet Shortcuts',['https://dgtal-team.github.io/doc-nightly/moduleFrechetShortcut.html',1,'']]],
  ['simple_203d_20volume_20viewer_20in_20less_20than_2050_20lines_16',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageGridVolume3dVolViewer.html',1,'']]],
  ['simple_20image_20manipulations_17',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageManipulations.html',1,'']]],
  ['simple_20mesh_18',['Manipulating Simple Mesh',['https://dgtal-team.github.io/doc-nightly/moduleMesh.html',1,'']]],
  ['slice2vol_19',['slice2vol',['../slice2vol.html',1,'']]],
  ['some_20simple_20image_20manipulations_20',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['https://dgtal-team.github.io/doc-nightly/tutoImageManipulations.html',1,'']]],
  ['source_20code_20management_20in_20dgtal_21',['Git/Github source code management in DGtal',['https://dgtal-team.github.io/doc-nightly/moduleFAQGit.html',1,'']]],
  ['space_22',['Embedding n-dimensional DEC structures into m-dimensional space',['https://dgtal-team.github.io/doc-nightly/moduleDECEmbedding.html',1,'']]],
  ['space_20and_20topology_20unoriented_20and_20oriented_20cells_20incidence_23',['Cellular grid space and topology, unoriented and oriented cells, incidence',['https://dgtal-team.github.io/doc-nightly/moduleCellularTopology.html',1,'']]],
  ['spaces_24',['Sets of points in digital spaces',['https://dgtal-team.github.io/doc-nightly/moduleDigitalSets.html',1,'']]],
  ['spaces_20digital_20metric_20spaces_20and_20related_20concepts_25',['Metric Spaces, Digital Metric Spaces and Related Concepts',['https://dgtal-team.github.io/doc-nightly/moduleMetrics.html',1,'']]],
  ['spaces_20points_20vectors_20and_20domains_26',['Digital Spaces, Points, Vectors and Domains',['https://dgtal-team.github.io/doc-nightly/moduleSpacePointVectorDomain.html',1,'']]],
  ['statisticsestimators_27',['statisticsEstimators',['../statisticsEstimators.html',1,'']]],
  ['straight_20lines_20and_20segments_28',['Digital straight lines and segments',['https://dgtal-team.github.io/doc-nightly/moduleArithDSSReco.html',1,'']]],
  ['straight_20lines_20and_20subsegments_29',['Patterns, digital straight lines and subsegments',['https://dgtal-team.github.io/doc-nightly/moduleDigitalStraightness.html',1,'']]],
  ['stream_20mechanism_30',['Limited interaction when using selection with QGLViewer Viewer3D stream mechanism',['https://dgtal-team.github.io/doc-nightly/moduleQGLInteraction.html',1,'']]],
  ['stream_20mechanism_20for_20displaying_202d_20digital_20objects_31',['Board2D: a stream mechanism for displaying 2D digital objects',['https://dgtal-team.github.io/doc-nightly/moduleBoard2D.html',1,'']]],
  ['stream_20mechanism_20for_20displaying_203d_20dgtal_20objects_32',['Display3D: a stream mechanism for displaying 3D DGtal objects',['https://dgtal-team.github.io/doc-nightly/moduleDisplay3D.html',1,'']]],
  ['structures_33',['Analysis of one-dimensional discrete structures',['https://dgtal-team.github.io/doc-nightly/moduleGridCurveAnalysis.html',1,'']]],
  ['structures_20into_20m_20dimensional_20space_34',['Embedding n-dimensional DEC structures into m-dimensional space',['https://dgtal-team.github.io/doc-nightly/moduleDECEmbedding.html',1,'']]],
  ['subsegments_35',['Patterns, digital straight lines and subsegments',['https://dgtal-team.github.io/doc-nightly/moduleDigitalStraightness.html',1,'']]],
  ['surface_20area_20estimation_36',['Tutorial: Surface area estimation',['https://dgtal-team.github.io/doc-nightly/tutoAreaSurface.html',1,'']]],
  ['surface_20estimators_20from_20surfel_20functors_37',['Local digital surface estimators from surfel functors',['https://dgtal-team.github.io/doc-nightly/LocalEstimatorsFromSurfel.html',1,'']]],
  ['surfaces_38',['surfaces',['https://dgtal-team.github.io/doc-nightly/moduleDigitalSurfaces.html',1,'Digital surfaces'],['https://dgtal-team.github.io/doc-nightly/moduleDigitalSurfaceHelpers.html',1,'Helpers for digital surfaces']]],
  ['surfaces_20surfel_20predicates_39',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts2.html',1,'']]],
  ['surfel_20functors_40',['Local digital surface estimators from surfel functors',['https://dgtal-team.github.io/doc-nightly/LocalEstimatorsFromSurfel.html',1,'']]],
  ['surfel_20predicates_41',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['https://dgtal-team.github.io/doc-nightly/packageTopologyConcepts2.html',1,'']]],
  ['systems_42',['How to use DGtal in my own project with other build systems?',['https://dgtal-team.github.io/doc-nightly/moduleHowToUseDGtal-qmake.html',1,'']]]
];
